---
title: "Functions for PSA"
author: "Karan Ketan Shah"
date: "2024-04-23"
output: html_document
---


```{r , include=FALSE}
rm(list = ls())  # remove any variables in R's memory
options(scipen = 999)
```

# Load libraries
```{r load libraries, echo=FALSE}
library(tidyverse)
library(dplyr)
library(readxl)
library(SciViews)
library(dampack)
library(writexl)
library(ggplot2)
library(reshape2)
library(summarytools)
library(cowplot)

```

# Set directory
```{r set directory, echo=FALSE}
modelsloc <- 'C:/Users/kshah/OneDrive - The University of Sydney (Staff)/Model/Markov vs microsim/Model/Markov model/R'
inputsloc <-  'C:/Users/kshah/OneDrive - The University of Sydney (Staff)/Markov vs microsim/Model/Inputs'

source(file.path("C:/Users/kshah/OneDrive - The University of Sydney (Staff)/Markov vs microsim/Model/Markov model/R/Functions.R"))
```

# Load inputs
```{r load R inputs, echo=FALSE}
load(file.path(inputsloc, 'costs.Rdata'))
load(file.path(inputsloc,'Utility.RData'))
load(file.path(inputsloc,'transition_probs.RData'))

# Capture all objects into a list
l_params_all <- list()
for (obj_name in ls()) {
  l_params_all[[obj_name]] <- get(obj_name)
}

#* Store the parameter names into a vector
v_names_params <- names(l_params_all)

```

# Settings
```{r model start, echo=FALSE}
## Strategy names
v_names_str <-c("Current clinical practice", "Shift in clinical practice") # strategy names
n_str <-length(v_names_str)        # number of strategies

#everyone will begin on the waitlist
n_cycles <-  80 # number of cycles, mean age is 63 so upto 83 years of life expectancy
n_c <- 1 # number of people

# v_cycles_tunnel <- 1:n_tunnel_size # vector with cycles for tunnels
cycle_length <- 0.25

tp_SVR <- 1 - (1 - 0.965) ^ cycle_length # efficacy of DAA agents for patients with hepC
per_effect_hcv <- 0.05/4 # increase in % of kidney transplantation in proposed policy. These patients will directly go to HCV health state
per_effect_increased_risk_behaviours <- 0.02/4 # increase in % of kidney transplantation in proposed policy. These patients will directly go to SCD health states

tp_graft_failure <- round(tp_graft_failure, 4)

c_diagosis_proposed_policy <- 3348.9
```

# Decision model
```{r}
decision_model <- function(l_params_all, verbose = FALSE) {
  with(
    as.list(l_params_all),
    {
      # names of the health states in the model
      v_names_health_states <-
        c(
          "On waitlist",
          "DBD SCD good",
          "DBD SCD moderate",
          "DBD SCD poor",
          "DBD ECD good",
          "DBD ECD moderate",
          "DBD ECD poor",
          "DCD good",
          "DCD moderate",
          "DCD poor",
          "Good graft DBD SCD",
          "Good graft DBD ECD",
          "Good graft DCD",
          "Moderate graft DBD SCD",
          "Moderate graft DBD ECD",
          "Moderate graft DCD",
          "Poor graft DBD SCD",
          "Poor graft DBD ECD",
          "Poor graft DCD",
          "Off waitlist",
          "HIV",
          "HBV",
          "Hep B Comp cirr",
          "Hep B Decomp cirr",
          "Hep B HCC",
          "Spon clearance",
          "HCV",
          "Hep C comp cirr",
          "Hep C Decomp cirr",
          "Hep C HCC",
          "SVR",
          "Liver transplant 3",
          "Liver transplant 6",
          "Liver transplant 9",
          "Liver transplant 12",
          "Liver transplant yr 2",
          "Death on waitlist",
          "Death off waitlist",
          "Death after graft failure",
          "Death w functioning graft",
          "Death end stage liver"
        )
      
      n_states <- length(v_names_health_states) # number of health states
      v_m_on_waitlist <-
        c(1, rep(0, 40)) # all starting on waitlist in year 1
      
      
      # initialise cohort trace for state-residence dependent cSTM
      m_M_current_practice <- matrix(
        0,
        nrow = (n_cycles + 1),
        ncol = n_states,
        dimnames = list(0:n_cycles, v_names_health_states)
      )
      
      # store the initial state vector in the first row of the cohort trace
      m_M_current_practice[1,] <- v_m_on_waitlist
      
      ##* initialize cohort trace for proposed strategy
      #* structure and initial states are the same as for current practice
      m_M_proposed_practice <- m_M_current_practice
      
      m_P_current_practice <- matrix(
        0,
        nrow = n_states,
        ncol = n_states,
        dimnames = list(v_names_health_states,
                        v_names_health_states)
      )
      
      m_P_proposed_practice <- m_P_current_practice
      
      
      # formula to calculate transplant and suspension transition from the waitlist for each of the blood groups
      calculate_bloodgrp_transitions_transplant <-
        function(tp_transplant, pro_blood_grp) {
          return(
            tp_transplant_bloodgrp_A * pro_blood_grp_A +
              tp_transplant_bloodgrp_B * pro_blood_grp_B +
              tp_transplant_bloodgrp_AB * pro_blood_grp_AB +
              tp_transplant_bloodgrp_O * pro_blood_grp_O
          )
        }
      
      calculate_bloodgrp_transitions_suspension <-
        function(tp_suspension, pro_blood_grp) {
          return(
            tp_off_waitlist_bloodgrp_A * pro_blood_grp_A +
              tp_off_waitlist_bloodgrp_B * pro_blood_grp_B +
              tp_off_waitlist_bloodgrp_AB * pro_blood_grp_AB +
              tp_off_waitlist_bloodgrp_O * pro_blood_grp_O
          )
        }
      
      # Calculate transitions for transplant and suspension using blood group proportions
      bloodgrp_transition_transplant_DBDSCD = round(
        calculate_bloodgrp_transitions_transplant(tp_transplant, pro_blood_grp) * pro_DBDSCD,
        3
      )
      bloodgrp_transition_transplant_DBDECD = round(
        calculate_bloodgrp_transitions_transplant(tp_transplant, pro_blood_grp) * pro_DBDECD,
        3
      )
      bloodgrp_transition_transplant_DCD = round(
        calculate_bloodgrp_transitions_transplant(tp_transplant, pro_blood_grp) * pro_DCD,
        3
      )
      
      bloodgrp_transition_suspension_DBDSCD = round(
        calculate_bloodgrp_transitions_suspension(tp_suspension, pro_blood_grp) * pro_DBDSCD,
        3
      )
      bloodgrp_transition_suspension_DBDECD = round(
        calculate_bloodgrp_transitions_suspension(tp_suspension, pro_blood_grp) * pro_DBDECD,
        3
      )
      bloodgrp_transition_suspension_DCD = round(
        calculate_bloodgrp_transitions_suspension(tp_suspension, pro_blood_grp) * pro_DCD,
        3
      )
      
      susp_prob <-
        bloodgrp_transition_suspension_DBDSCD + bloodgrp_transition_suspension_DBDECD + bloodgrp_transition_suspension_DCD
      
      tx_fail_to_off_wlst <-
        round(
          bloodgrp_transition_transplant_DBDSCD * tp_graft_failure +
            bloodgrp_transition_transplant_DBDECD * tp_graft_failure +
            bloodgrp_transition_transplant_DCD * tp_graft_failure,
          4
        )
      
      proposed_pol_suspen <- round(per_effect_increased_risk_behaviours * tp_graft_failure, 3)

      ### Initialise transition probability matrix for strategy current practice ----

      #1. From waitlist
      #
      m_P_current_practice["On waitlist", "Death on waitlist"] <-
        n_death_waitlist
      
      #
      m_P_current_practice["On waitlist", "DBD SCD good"] <-
        round(
          bloodgrp_transition_transplant_DBDSCD * (1 - pro_DBDSCD_mg - pro_DBDSCD_pg - tp_graft_failure),4)
      
      m_P_current_practice["On waitlist", "DBD SCD moderate"] <-
        round(bloodgrp_transition_transplant_DBDSCD * pro_DBDSCD_mg, 4)
      
      m_P_current_practice["On waitlist", "DBD SCD poor"] <-
        round(bloodgrp_transition_transplant_DBDSCD * pro_DBDSCD_pg, 4)
      
      #
      m_P_current_practice["On waitlist", "DBD ECD good"] <-
        round(
          bloodgrp_transition_transplant_DBDECD * (1 - pro_DBDECD_mg - pro_DBDECD_pg - tp_graft_failure),4)
      
      m_P_current_practice["On waitlist", "DBD ECD moderate"] <-
        round(bloodgrp_transition_transplant_DBDECD * pro_DBDECD_mg, 4)
      
      m_P_current_practice["On waitlist", "DBD ECD poor"] <-
        round(bloodgrp_transition_transplant_DBDECD * pro_DBDECD_pg, 4)
      
      #
      m_P_current_practice["On waitlist", "DCD good"] <-
        round(
          bloodgrp_transition_transplant_DCD * (1 - pro_DCD_mg - pro_DCD_pg - tp_graft_failure),4)
      
      m_P_current_practice["On waitlist", "DCD moderate"] <-
        round(bloodgrp_transition_transplant_DCD * pro_DCD_mg, 4)
      
      m_P_current_practice["On waitlist", "DCD poor"] <-
        round(bloodgrp_transition_transplant_DCD * pro_DCD_pg, 4)
      
      
      # Transition to suspension off the waitlist
      m_P_current_practice["On waitlist", "Off waitlist"] <-
        round(susp_prob + tx_fail_to_off_wlst, 4)
      
      
      # Sum of all transitions out of the current waitlist state
      total_trans_prob =
        m_P_current_practice["On waitlist", "Death on waitlist"] +
        m_P_current_practice["On waitlist", "DBD SCD good"] +
        m_P_current_practice["On waitlist", "DBD SCD moderate"] +
        m_P_current_practice["On waitlist", "DBD SCD poor"] +
        m_P_current_practice["On waitlist", "DBD ECD good"] +
        m_P_current_practice["On waitlist", "DBD ECD moderate"] +
        m_P_current_practice["On waitlist", "DBD ECD poor"] +
        m_P_current_practice["On waitlist", "DCD good"] +
        m_P_current_practice["On waitlist", "DCD moderate"] +
        m_P_current_practice["On waitlist", "DCD poor"] +
        m_P_current_practice["On waitlist", "Off waitlist"]
      
      m_P_current_practice["On waitlist", "On waitlist"] <-   1 - total_trans_prob
      
      
      #2. From kidney transplant
      ## DBD SCD good
      ### to hepatitis B
      m_P_current_practice["DBD SCD good", "HBV" ] <-
        round(tp_HBV_current_practice, 4)
      
      ### to hepatitis C
      m_P_current_practice["DBD SCD good", "HCV" ] <-
        round(tp_HCV_current_practice, 5)
      
      total_trans_prob_DBDSCD_good =
        m_P_current_practice["DBD SCD good", "HBV"] +
        m_P_current_practice["DBD SCD good", "HCV"]
      
      ### good graft function post kidney transplant. All the remaining patients would move here.
      m_P_current_practice["DBD SCD good", "Good graft DBD SCD"] <-
        1 - total_trans_prob_DBDSCD_good
      
      
      ## DBD SCD moderate
      ### to hepatitis B
      m_P_current_practice["DBD SCD moderate", "HBV"] <-
        round(tp_HBV_current_practice, 4)
      
      ### to hepatitis C
      m_P_current_practice["DBD SCD moderate", "HCV"] <-
        round(tp_HCV_current_practice, 5)
      
      
      total_trans_prob_DBDSCD_moderate =
        m_P_current_practice["DBD SCD moderate", "HBV"] +
        m_P_current_practice["DBD SCD moderate", "HCV"]
      
      ### moderate graft function post kidney transplant. All the remaining patients would move here.
      m_P_current_practice["DBD SCD moderate", "Moderate graft DBD SCD"] <-
        1 - total_trans_prob_DBDSCD_moderate
      
      
      ## DBD SCD poor
      ### to hepatitis B
      m_P_current_practice["DBD SCD poor", "HBV"] <-
        round(tp_HBV_current_practice, 4)
      
      ### to hepatitis C
      m_P_current_practice["DBD SCD poor", "HCV"] <-
        round(tp_HCV_current_practice, 5)
      
      
      total_trans_prob_DBDSCD_poor =
        m_P_current_practice["DBD SCD poor", "HBV"] +
        m_P_current_practice["DBD SCD poor", "HCV"]
      
      ### poor graft function post kidney transplant. All the remaining patients would move here.
      m_P_current_practice["DBD SCD poor", "Poor graft DBD SCD"] <-
        1 - total_trans_prob_DBDSCD_poor
      
      
      ## From DBD ECD good
      ### to hepatitis B
      m_P_current_practice["DBD ECD good", "HBV"] <-
        round(tp_HBV_current_practice, 4)
      
      ### to hepatitis C
      m_P_current_practice["DBD ECD good", "HCV"] <-
        round(tp_HCV_current_practice, 5)
      
      
      total_trans_prob_DBDECD_good =
        
        m_P_current_practice["DBD ECD good", "HBV"] +
        m_P_current_practice["DBD ECD good", "HCV"]
      
      ### good graft function post kidney transplant. All the remaining patients would move here.
      m_P_current_practice["DBD ECD good", "Good graft DBD ECD"] <-
        1 - total_trans_prob_DBDECD_good
      
      
      ## From DBD ECD moderate
      ### to hepatitis B
      m_P_current_practice["DBD ECD moderate", "HBV"] <-
        round(tp_HBV_current_practice, 4)
      
      ### to hepatitis C
      m_P_current_practice["DBD ECD moderate", "HCV"] <-
        round(tp_HCV_current_practice, 5)
      
      
      total_trans_prob_DBDECD_moderate =
        m_P_current_practice["DBD ECD moderate", "HBV"] +
        m_P_current_practice["DBD ECD moderate", "HCV"]
      
      ### moderate graft function post kidney transplant. All the remaining patients would move here.
      m_P_current_practice["DBD ECD moderate", "Moderate graft DBD ECD"] <-
        1 - total_trans_prob_DBDECD_moderate
      
      
      ## From DBD ECD poor
      ### to hepatitis B
      m_P_current_practice["DBD ECD poor", "HBV"] <-
        round(tp_HBV_current_practice, 4)
      
      ### to hepatitis C
      m_P_current_practice["DBD ECD poor", "HCV"] <-
        round(tp_HCV_current_practice, 5)
      
      
      total_trans_prob_DBDECD_poor =
        m_P_current_practice["DBD ECD poor", "HBV"] +
        m_P_current_practice["DBD ECD poor", "HCV"]
      
      ### poor graft function post kidney transplant. All the remaining patients would move here.
      m_P_current_practice["DBD ECD poor", "Poor graft DBD ECD"] <-
        1 - total_trans_prob_DBDECD_poor
      
      
      ## From DCD good
      ### to hepatitis B
      m_P_current_practice["DCD good", "HBV"] <-
        round(tp_HBV_current_practice, 4)
      
      ### to hepatitis C
      m_P_current_practice["DCD good", "HCV"] <-
        round(tp_HCV_current_practice, 5)
      
      
      total_trans_prob_DCD_good =
        m_P_current_practice["DCD good", "HBV"] +
        m_P_current_practice["DCD good", "HCV"]
      
      ### good graft function post kidney transplant. All the remaining patients would move here.
      m_P_current_practice["DCD good", "Good graft DCD"] <-
        1 - total_trans_prob_DCD_good
      
      
      ## From DCD moderate
      ### to hepatitis B
      m_P_current_practice["DCD moderate", "HBV"] <-
        round(tp_HBV_current_practice, 4)
      
      ### to hepatitis C
      m_P_current_practice["DCD moderate", "HCV"] <-
        round(tp_HCV_current_practice, 5)
      
      
      total_trans_prob_DCD_moderate =
        m_P_current_practice["DCD moderate", "HBV"] +
        m_P_current_practice["DCD moderate", "HCV"]
      
      ### moderate graft function post kidney transplant. All the remaining patients would move here.
      m_P_current_practice["DCD moderate", "Moderate graft DCD"] <-
        1 - total_trans_prob_DCD_moderate
      
      
      ## From DCD poor
      ### to hepatitis B
      m_P_current_practice["DCD poor", "HBV"] <-
        round(tp_HBV_current_practice, 4)
      ### to hepatitis C
      m_P_current_practice["DCD poor", "HCV"] <-
        round(tp_HCV_current_practice, 5)
      
      
      total_trans_prob_DCD_poor =
        m_P_current_practice["DCD poor", "HBV"] +
        m_P_current_practice["DCD poor", "HCV"]
      
      ### poor graft function post kidney transplant. All the remaining patients would move here.
      m_P_current_practice["DCD poor", "Poor graft DCD"] <-
        1 - total_trans_prob_DCD_poor
      
      
      #3. From good graft DBD SCD
      m_P_current_practice["Good graft DBD SCD", "Moderate graft DBD SCD"] <-
        round(tp_gm_DBDSCD, 4)
      m_P_current_practice["Good graft DBD SCD", "Poor graft DBD SCD"] <-
        round(tp_gp_DBDSCD, 4)
      m_P_current_practice["Good graft DBD SCD", "Death w functioning graft"] <-
        round(tp_gd_DBDSCD, 4)
      
      trans_good_other <-
        m_P_current_practice["Good graft DBD SCD", "Moderate graft DBD SCD"] +
        m_P_current_practice["Good graft DBD SCD", "Poor graft DBD SCD"] +
        m_P_current_practice["Good graft DBD SCD", "Death w functioning graft"]
      
      m_P_current_practice["Good graft DBD SCD", "Good graft DBD SCD"] <-
        1 - trans_good_other
      
      
      #4. From moderate graft DBD SCD
      m_P_current_practice["Moderate graft DBD SCD", "Poor graft DBD SCD"] <-
        round(tp_mp_DBDSCD, 4)
      m_P_current_practice["Moderate graft DBD SCD", "Death w functioning graft"] <-
        round(tp_md_DBDSCD, 4)
      
      trans_moderate_other <-
        m_P_current_practice["Moderate graft DBD SCD", "Poor graft DBD SCD"] +
        m_P_current_practice["Moderate graft DBD SCD", "Death w functioning graft"]
      
      m_P_current_practice["Moderate graft DBD SCD", "Moderate graft DBD SCD"] <-
        1 - trans_moderate_other
      
      
      #5. From poor graft  DBD SCD
      m_P_current_practice["Poor graft DBD SCD", "Off waitlist"] <-
        round(tp_graft_failure, 4)
      
      m_P_current_practice["Poor graft DBD SCD", "Death after graft failure"] <-
        round(tp_peskd_DBDSCD, 4)
      
      m_P_current_practice["Poor graft DBD SCD", "Death w functioning graft"] <-
        round(tp_pd_DBDSCD, 4)
      
      trans_poor_to_other <-
        m_P_current_practice["Poor graft DBD SCD", "Off waitlist"] +
        m_P_current_practice["Poor graft DBD SCD", "Death after graft failure"] +
        m_P_current_practice["Poor graft DBD SCD", "Death w functioning graft"]
      
      m_P_current_practice["Poor graft DBD SCD", "Poor graft DBD SCD"] <-
        1 - trans_poor_to_other
      
      
      #6. From good graft DBD ECD
      m_P_current_practice["Good graft DBD ECD", "Moderate graft DBD ECD"] <-
        round(tp_gm_DBDECD, 4)
      m_P_current_practice["Good graft DBD ECD", "Poor graft DBD ECD"] <-
        round(tp_gp_DBDECD, 4)
      m_P_current_practice["Good graft DBD ECD", "Death w functioning graft"] <-
        round(tp_gd_DBDECD, 4)
      
      trans_good_other <-
        m_P_current_practice["Good graft DBD ECD", "Moderate graft DBD ECD"] +
        m_P_current_practice["Good graft DBD ECD", "Poor graft DBD ECD"] +
        m_P_current_practice["Good graft DBD ECD", "Death w functioning graft"]
      
      m_P_current_practice["Good graft DBD ECD", "Good graft DBD ECD"] <-
        1 - trans_good_other
      
      
      #7. From moderate graft DBD ECD
      m_P_current_practice["Moderate graft DBD ECD", "Poor graft DBD ECD"] <-
        round(tp_mp_DBDECD, 4)
      m_P_current_practice["Moderate graft DBD ECD", "Death w functioning graft"] <-
        round(tp_md_DBDECD, 4)
      
      trans_moderate_other <-
        m_P_current_practice["Moderate graft DBD ECD", "Poor graft DBD ECD"] +
        m_P_current_practice["Moderate graft DBD ECD", "Death w functioning graft"]
      
      m_P_current_practice["Moderate graft DBD ECD", "Moderate graft DBD ECD"] <-
        1 - trans_moderate_other
      
      
      #8. From poor graft  DBD ECD
      m_P_current_practice["Poor graft DBD ECD", "Off waitlist"] <-
        round(tp_graft_failure, 4)
      
      m_P_current_practice["Poor graft DBD ECD", "Death after graft failure"] <-
        round(tp_peskd_DBDECD, 4)
      
      m_P_current_practice["Poor graft DBD ECD", "Death w functioning graft"] <-
        round(tp_pd_DBDECD, 4)
      
      trans_poor_to_other <-
        m_P_current_practice["Poor graft DBD ECD", "Off waitlist"] +
        m_P_current_practice["Poor graft DBD ECD", "Death after graft failure"] +
        m_P_current_practice["Poor graft DBD ECD", "Death w functioning graft"]
      
      m_P_current_practice["Poor graft DBD ECD", "Poor graft DBD ECD"] <-
        1 - trans_poor_to_other
      
      
      #9. From good graft DCD
      m_P_current_practice["Good graft DCD", "Moderate graft DCD"] <-
        round(tp_gm_DCD, 4)
      m_P_current_practice["Good graft DCD", "Poor graft DCD"] <-
        round(tp_gp_DCD, 4)
      m_P_current_practice["Good graft DCD", "Death w functioning graft"] <-
        round(tp_gd_DCD, 4)
      
      trans_good_other <-
        m_P_current_practice["Good graft DCD", "Moderate graft DCD"] +
        m_P_current_practice["Good graft DCD", "Poor graft DCD"] +
        m_P_current_practice["Good graft DCD", "Death w functioning graft"]
      
      m_P_current_practice["Good graft DCD", "Good graft DCD"] <-
        1 - trans_good_other
      
      
      #10. From moderate graft DCD
      m_P_current_practice["Moderate graft DCD", "Poor graft DCD"] <-
        round(tp_mp_DCD, 4)
      m_P_current_practice["Moderate graft DCD", "Death w functioning graft"] <-
        round(tp_md_DCD, 4)
      
      trans_moderate_other <-
        m_P_current_practice["Moderate graft DCD", "Poor graft DCD"] +
        m_P_current_practice["Moderate graft DCD", "Death w functioning graft"]
      
      m_P_current_practice["Moderate graft DCD", "Moderate graft DCD"] <-
        1 - trans_moderate_other
      
      
      #11. From poor graft  DCD
      m_P_current_practice["Poor graft DCD", "Off waitlist"] <-
        round(tp_graft_failure, 4)
      
      m_P_current_practice["Poor graft DCD", "Death after graft failure"] <-
        round(tp_peskd_DCD, 4)
      
      m_P_current_practice["Poor graft DCD", "Death w functioning graft"] <-
        round(tp_pd_DCD, 4)
      
      trans_poor_to_other <-
        m_P_current_practice["Poor graft DCD", "Off waitlist"] +
        m_P_current_practice["Poor graft DCD", "Death after graft failure"] +
        m_P_current_practice["Poor graft DCD", "Death w functioning graft"]
      
      m_P_current_practice["Poor graft DCD", "Poor graft DCD"] <-
        1 - trans_poor_to_other
      
      
      #12. From temporary off-waitlist
      ## Transition to death on dialysis
      m_P_current_practice["Off waitlist", "Death off waitlist"] <-
        n_death_off_waitlist
      
      ## Transition back to the waitlist
      m_P_current_practice["Off waitlist", "On waitlist"] <-
        round(tp_back_on_waitlist, 3)
      
      ## Calculating the remaining probability after accounting for death and transition back to the waitlist
      total_trans_prob_off_waitlist <-
        round(m_P_current_practice["Off waitlist", "Death off waitlist"] + (m_P_current_practice["Off waitlist", "On waitlist"]), 3)
      
      m_P_current_practice["Off waitlist", "Off waitlist"] <-
        
        1 - total_trans_prob_off_waitlist
      
      
      #13. From HIV
      ## Death with functioning graft
      m_P_current_practice["HIV", "Death w functioning graft"] <-
        n_death_functioning_graft
      
      
      ## people who remain in HIV
      m_P_current_practice["HIV", "HIV"] <-
        1 - round(m_P_current_practice["HIV", "Death w functioning graft"], 3)
      
      
      #14. From HBV
      ## from HBV to death from other causes
      m_P_current_practice["HBV", "Death w functioning graft"] <-
        n_death_functioning_graft
      
      ## HBV to compensated cirrhosis
      m_P_current_practice["HBV", "Hep B Comp cirr"] <-
        round(tp_chb_cc_hepB, 5)
      
      ## HBV to spontaneous clearance
      m_P_current_practice["HBV", "Spon clearance"] <-
        round(tp_chb_sAgloss_hepB, 4)
      
      ## HBV to hepatocellular carcinoma
      m_P_current_practice["HBV", "Hep B HCC"] <- round(tp_chb_hcc, 7)
      
      trans_HBV_other <-
        m_P_current_practice["HBV", "Death w functioning graft"] +
        m_P_current_practice["HBV", "Hep B Comp cirr"] +
        m_P_current_practice["HBV", "Spon clearance"] +
        m_P_current_practice["HBV", "Hep B HCC"]
      
      m_P_current_practice["HBV", "HBV"] <-
        1 - trans_HBV_other
      
      
      #16. From HCV
      ## From HCV to death from other causes
      m_P_current_practice["HCV", "Death w functioning graft"] <-
        n_death_functioning_graft
      
      ## from HCV to compensated cirrhosis
      m_P_current_practice["HCV", "Hep C comp cirr"] <-
        round(tp_chc_cc_hepC, 5)
      
      
      ## from HCV to sustained virological response
      m_P_current_practice["HCV", "SVR"] <- round(tp_SVR, 3)
      
      trans_hcv_other <-
        m_P_current_practice["HCV", "Death w functioning graft"] +
        m_P_current_practice["HCV", "Hep C comp cirr"] +
        m_P_current_practice["HCV", "SVR"]
      
      ## people who continue to remain in HCV
      m_P_current_practice["HCV", "HCV"] <-
        1 - trans_hcv_other
      
      
      #17. From compensated cirrhosis Hep B
      ## From compensated cirrhosis to death from other causes
      m_P_current_practice["Hep B Comp cirr", "Death w functioning graft"] <-
        n_death_functioning_graft
      
      ## from compensated cirrhosis to death due to end stage liver disease
      m_P_current_practice["Hep B Comp cirr", "Death end stage liver"] <-
        round(tp_death_cc_hepB, 5)
      
      ## from compensated cirrhosis to decompensated cirrhosis
      m_P_current_practice["Hep B Comp cirr", "Hep B Decomp cirr"] <-
        round(tp_cc_dc_hepB, 4)
      
      ## from compensated cirrhosis to hepatocellular carcinoma
      m_P_current_practice["Hep B Comp cirr", "Hep B HCC"] <-
        round(tp_cc_hcc_hepB, 4)
      
      trans_comp_hepB <-
        m_P_current_practice["Hep B Comp cirr", "Death w functioning graft"] +
        m_P_current_practice["Hep B Comp cirr", "Death end stage liver"] +
        m_P_current_practice["Hep B Comp cirr", "Hep B Decomp cirr"] +
        m_P_current_practice["Hep B Comp cirr", "Hep B HCC"]
      
      m_P_current_practice["Hep B Comp cirr", "Hep B Comp cirr"] <-
        1 - trans_comp_hepB
      
      
      #18. From compensated cirrhosis Hep C
      ## From compensated cirrhosis to death from other causes
      m_P_current_practice["Hep C comp cirr", "Death w functioning graft"] <-
        n_death_functioning_graft
      
      ## from compensated cirrhosis to decompensated cirrhosis
      m_P_current_practice["Hep C comp cirr", "Hep C Decomp cirr"] <-
        round(tp_cc_dc_hepC, 4)
      
      ## from compensated cirrhosis to hepatocellular carcinoma
      m_P_current_practice["Hep C comp cirr", "Hep C HCC"] <-
        round(tp_cc_hcc_hepC, 4)
      
      trans_comp_hepC <-
        m_P_current_practice["Hep C comp cirr", "Death w functioning graft"] +
        m_P_current_practice["Hep C comp cirr", "Hep C Decomp cirr"] +
        m_P_current_practice["Hep C comp cirr", "Hep C HCC"]
      
      m_P_current_practice["Hep C comp cirr", "Hep C comp cirr"] <-
        1 - trans_comp_hepC
      
      
      #19. From decompensated cirrhosis Hep B
      ## From decompensated cirrhosis to death from other causes
      m_P_current_practice["Hep B Decomp cirr", "Death w functioning graft"] <-
        n_death_functioning_graft
      
      ## from decompemnsated cirrhosis to death due to end stage liver disease
      m_P_current_practice["Hep B Decomp cirr", "Death end stage liver"] <-
        round(tp_death_dc_hepB, 4)
      
      ## from decompensated cirrhosis to hepatocellular carcinoma
      m_P_current_practice["Hep B Decomp cirr", "Hep B HCC"] <-
        round(tp_dc_hcc_hepB, 4)
      
      ## from deoompensated cirrhosis to liver transplant
      m_P_current_practice["Hep B Decomp cirr", "Liver transplant 3"] <-
        round(tp_dc_lt_hepB, 4)
      
      trans_decom_hepB <-
        m_P_current_practice["Hep B Decomp cirr", "Death w functioning graft"] +
        m_P_current_practice["Hep B Decomp cirr", "Death end stage liver"] +
        m_P_current_practice["Hep B Decomp cirr", "Hep B HCC"] +
        m_P_current_practice["Hep B Decomp cirr", "Liver transplant 3"]
      
      ## people who continue to remain in decompensated cirrhosis
      m_P_current_practice["Hep B Decomp cirr", "Hep B Decomp cirr"] <-
        1 - trans_decom_hepB
      
      
      #20. From decompensated cirrhosis Hep C
      ## From decompensated cirrhosis to death from other causes
      m_P_current_practice["Hep C Decomp cirr", "Death w functioning graft"] <-
        n_death_functioning_graft
      
      ## from decompemnsated cirrhosis to death due to end stage liver disease
      m_P_current_practice["Hep C Decomp cirr", "Death end stage liver"] <-
        round(tp_death_dc_hepC, 4)
      
      ## from decompensated cirrhosis to hepatocellular carcinoma
      m_P_current_practice["Hep C Decomp cirr", "Hep C HCC"] <-
        round(tp_dc_hcc_hepC, 4)
      
      ## from decompensated cirrhosis to liver transplant
      m_P_current_practice["Hep C Decomp cirr", "Liver transplant 3"] <-
        round(tp_dc_lt_hepC, 4)
      
      trans_decom_hepC <-
        m_P_current_practice["Hep C Decomp cirr", "Death w functioning graft"] +
        m_P_current_practice["Hep C Decomp cirr", "Death end stage liver"] +
        m_P_current_practice["Hep C Decomp cirr", "Hep C HCC"] +
        m_P_current_practice["Hep C Decomp cirr", "Liver transplant 3"]
      
      m_P_current_practice["Hep C Decomp cirr", "Hep C Decomp cirr"] <-
        1 - trans_decom_hepC
      
      
      #21. From hepatocellular carcinoma Hep B
      ## from hepatocellular carcinoma to death from other causes
      m_P_current_practice["Hep B HCC", "Death w functioning graft"] <-
        n_death_functioning_graft
      
      ## from hepatocellular carcinoma to death due to end stage liver disease
      m_P_current_practice["Hep B HCC", "Death end stage liver"] <-
        round(tp_death_hcc_hepB, 4)
      
      ## from hepatocellular carcinoma to liver transplant
      m_P_current_practice["Hep B HCC", "Liver transplant 3"] <-
        round(tp_hcc_lt_hepB, 4)
      
      trans_hcc_hepB <-
        m_P_current_practice["Hep B HCC", "Death w functioning graft"] +
        m_P_current_practice["Hep B HCC", "Death end stage liver"] +
        m_P_current_practice["Hep B HCC", "Liver transplant 3"]
      
      m_P_current_practice["Hep B HCC", "Hep B HCC"] <-
        1 - trans_hcc_hepB
      
      
      #22. From hepatocellular carcinoma Hep C
      ## from hepatocellular carcinoma to death from other causes
      m_P_current_practice["Hep C HCC", "Death w functioning graft"] <-
        n_death_functioning_graft
      
      ## from hepatocellular carcinoma to death due to end stage liver disease
      m_P_current_practice["Hep C HCC", "Death end stage liver"] <-
        round(tp_death_hcc_hepC, 4)
      
      ## from hepatocellular carcinoma to liver transplant
      m_P_current_practice["Hep C HCC", "Liver transplant 3"] <-
        round(tp_hcc_lt_hepC, 4)
      
      trans_hcc_hepC <-
        m_P_current_practice["Hep C HCC", "Death w functioning graft"] +
        m_P_current_practice["Hep C HCC", "Death end stage liver"] +
        m_P_current_practice["Hep C HCC", "Liver transplant 3"]
      
      m_P_current_practice["Hep C HCC", "Hep C HCC"] <-
        1 - trans_hcc_hepC
      
      
      #23. From spontaneous clearance
      ## from spon clearance to death from other causes
      m_P_current_practice["Spon clearance", "Death w functioning graft"] <-
        n_death_functioning_graft
      
      trans_sponclear <-
        m_P_current_practice["Spon clearance", "Death w functioning graft"]
      
      m_P_current_practice["Spon clearance", "Spon clearance"] <-
        1 - trans_sponclear
      
      
      #24. From SVR
      ## from SVR to death from other causes
      m_P_current_practice["SVR", "Death w functioning graft"] <-
        n_death_functioning_graft
      
      trans_svr <-
        m_P_current_practice["SVR", "Death w functioning graft"]
      
      m_P_current_practice["SVR", "SVR"] <- 1 - trans_svr
      
      
      #25. From liver transplant
      ## Liver transplant year 1: 3 months
      m_P_current_practice["Liver transplant 3", "Death end stage liver"] <-
        round(tp_death_LT, 4)
      
      total_outgoing <-
        m_P_current_practice["Liver transplant 3", "Death end stage liver"]
      
      m_P_current_practice["Liver transplant 3", "Liver transplant 6"] <-
        1 - total_outgoing
      
      
      #26. from LT 6 to death
      m_P_current_practice["Liver transplant 6", "Death end stage liver"] <-
        round(tp_death_LT, 4)
      
      total_outgoing <-
        m_P_current_practice["Liver transplant 6", "Death end stage liver"]
      
      m_P_current_practice["Liver transplant 6", "Liver transplant 9"] <-
        1 - total_outgoing
      
      #27. from LT 9 to death
      m_P_current_practice["Liver transplant 9", "Death end stage liver"] <-
        round(tp_death_LT, 4)
      
      total_outgoing <-
        m_P_current_practice["Liver transplant 9", "Death end stage liver"]
      
      m_P_current_practice["Liver transplant 9", "Liver transplant 12"] <-
        1 - total_outgoing
      
      #28. from LT 12 to death
      m_P_current_practice["Liver transplant 12", "Death end stage liver"] <-
        round(tp_death_LT, 4)
      
      total_outgoing <-
        m_P_current_practice["Liver transplant 12", "Death end stage liver"]
      
      
      m_P_current_practice["Liver transplant 12", "Liver transplant yr 2"] <-
        1 - total_outgoing
      
      
      
      #29. Liver transplant Year 2+
      # Transition from "Liver transplant yr 2" to "Death end stage liver"
      m_P_current_practice["Liver transplant yr 2", "Death end stage liver"] <-
        round(tp_death_LT, 4)
      
      trans_lt2 <-
        m_P_current_practice["Liver transplant yr 2", "Death end stage liver"]
      
      m_P_current_practice["Liver transplant yr 2", "Liver transplant yr 2"] <-
        1 - trans_lt2
      
      
      #30. Death
      m_P_current_practice["Death on waitlist", "Death on waitlist"] <-
        1
      
      m_P_current_practice["Death off waitlist", "Death off waitlist"] <-
        1
      
      m_P_current_practice["Death w functioning graft", "Death w functioning graft"] <-
        1
      
      m_P_current_practice["Death after graft failure", "Death after graft failure"] <-
        1
      
      
      m_P_current_practice["Death end stage liver", "Death end stage liver"] <-
        1
      
      
      ### Initialize transition probability matrix for strategy proposed practice ----
      #1. From waitlist
      m_P_proposed_practice["On waitlist", "Death on waitlist"] <-
        n_death_waitlist
      
      ## Transitions to transplant states
      m_P_proposed_practice["On waitlist", "DBD SCD good"] <-
        round(
          bloodgrp_transition_transplant_DBDSCD * (1 - pro_DBDSCD_mg - pro_DBDSCD_pg - tp_graft_failure),
          4
        ) +
        round(
          per_effect_increased_risk_behaviours * (1 - pro_DBDSCD_mg - pro_DBDSCD_pg - tp_graft_failure),
          4
        )
      
      m_P_proposed_practice["On waitlist", "DBD SCD moderate"] <-
        round(pro_DBDSCD_mg * bloodgrp_transition_transplant_DBDSCD, 4)  +
        round(pro_DBDSCD_mg * per_effect_increased_risk_behaviours, 4)
      
      m_P_proposed_practice["On waitlist", "DBD SCD poor"] <-
        round(pro_DBDSCD_pg * bloodgrp_transition_transplant_DBDSCD, 4) +
        round(pro_DBDSCD_pg * per_effect_increased_risk_behaviours, 4)
      
      
      m_P_proposed_practice["On waitlist", "DBD ECD good"] <-
        round(
          bloodgrp_transition_transplant_DBDECD * (1 - pro_DBDECD_mg - pro_DBDECD_pg - tp_graft_failure),
          4
        )
      
      m_P_proposed_practice["On waitlist", "DBD ECD moderate"] <-
        round(pro_DBDECD_mg * bloodgrp_transition_transplant_DBDECD, 4)
      
      m_P_proposed_practice["On waitlist", "DBD ECD poor"] <-
        round(pro_DBDECD_pg * bloodgrp_transition_transplant_DBDECD, 4)
      
      
      m_P_proposed_practice["On waitlist", "DCD good"] <-
        round(
          bloodgrp_transition_transplant_DCD * (1 - pro_DCD_mg - pro_DCD_pg - tp_graft_failure),
          4
        )
      
      m_P_proposed_practice["On waitlist", "DCD moderate"] <-
        round(pro_DCD_mg * bloodgrp_transition_transplant_DCD, 4)
      
      m_P_proposed_practice["On waitlist", "DCD poor"] <-
        round(pro_DCD_pg * bloodgrp_transition_transplant_DCD, 4)
      
      
      m_P_proposed_practice["On waitlist", "HCV"] <- per_effect_hcv
      
      
      m_P_proposed_practice["On waitlist", "Off waitlist"] <-
        round(susp_prob + tx_fail_to_off_wlst + proposed_pol_suspen, 4)
      
      
      
      ## Sum of all transitions out of the current waitlist state
      total_trans_prob =
        m_P_proposed_practice["On waitlist", "Death on waitlist"] +
        m_P_proposed_practice["On waitlist", "DBD SCD good"] +
        m_P_proposed_practice["On waitlist", "DBD SCD moderate"] +
        m_P_proposed_practice["On waitlist", "DBD SCD poor"] +
        m_P_proposed_practice["On waitlist", "DBD ECD good"] +
        m_P_proposed_practice["On waitlist", "DBD ECD moderate"] +
        m_P_proposed_practice["On waitlist", "DBD ECD poor"] +
        m_P_proposed_practice["On waitlist", "DCD good"] +
        m_P_proposed_practice["On waitlist", "DCD moderate"] +
        m_P_proposed_practice["On waitlist", "DCD poor"] +
        m_P_proposed_practice["On waitlist", "HCV"] +
        m_P_proposed_practice["On waitlist", "Off waitlist"]
      
      m_P_proposed_practice["On waitlist", "On waitlist"] <-
        round(1 - total_trans_prob, 5)
      
      
      #2. From kidney transplant
      ## DBD SCD good
      ### to HIV
      m_P_proposed_practice["DBD SCD good", "HIV"] <-
        round(tp_HIV_proposed_practice, 7)
      
      ### to hepatitis B
      m_P_proposed_practice["DBD SCD good", "HBV"] <-
        round(tp_HBV_proposed_practice, 4)
      
      ### to hepatitis C
      m_P_proposed_practice["DBD SCD good", "HCV"] <-
        round(tp_HCV_proposed_practice, 5)
      
      total_trans_prob_DBDSCD_good =
        m_P_proposed_practice["DBD SCD good", "HIV"] +
        m_P_proposed_practice["DBD SCD good", "HBV"] +
        m_P_proposed_practice["DBD SCD good", "HCV"]
      
      ### good graft function post kidney transplant. All the remaining patients would move here.
      m_P_proposed_practice["DBD SCD good", "Good graft DBD SCD"] <-
        1 - total_trans_prob_DBDSCD_good
      
      
      ## DBD SCD moderate
      ### to HIV
      m_P_proposed_practice["DBD SCD moderate", "HIV"] <-
        round(tp_HIV_proposed_practice, 7)
      
      ### to hepatitis B
      m_P_proposed_practice["DBD SCD moderate", "HBV"] <-
        round(tp_HBV_proposed_practice, 4)
      
      ### to hepatitis C
      m_P_proposed_practice["DBD SCD moderate", "HCV"] <-
        round(tp_HCV_proposed_practice, 5)
      
      total_trans_prob_DBDSCD_moderate =
        m_P_proposed_practice["DBD ECD moderate", "HIV"] +
        m_P_proposed_practice["DBD SCD moderate", "HBV"] +
        m_P_proposed_practice["DBD SCD moderate", "HCV"]
      
      ### moderate graft function post kidney transplant. All the remaining patients would move here.
      m_P_proposed_practice["DBD SCD moderate", "Moderate graft DBD SCD"] <-
        1 - total_trans_prob_DBDSCD_moderate
      
      
      
      ## DBD SCD poor
      ### to HIV
      m_P_proposed_practice["DBD SCD poor", "HIV"] <-
        round(tp_HIV_proposed_practice, 7)
      
      ### to hepatitis B
      m_P_proposed_practice["DBD SCD poor", "HBV"] <-
        round(tp_HBV_proposed_practice, 4)
      
      ### to hepatitis C
      m_P_proposed_practice["DBD SCD poor", "HCV"] <-
        round(tp_HCV_proposed_practice, 5)
      
      total_trans_prob_DBDSCD_poor =
        m_P_proposed_practice["DBD SCD poor", "HIV"] +
        m_P_proposed_practice["DBD SCD poor", "HBV"] +
        m_P_proposed_practice["DBD SCD poor", "HCV"]
      
      ### poor graft function post kidney transplant. All the remaining patients would move here.
      m_P_proposed_practice["DBD SCD poor", "Poor graft DBD SCD"] <-
        1 - total_trans_prob_DBDSCD_poor
      
      
      ## From DBD ECD good
      ### to HIV
      m_P_proposed_practice["DBD ECD good", "HIV"] <-
        round(tp_HIV_proposed_practice, 7)
      
      ### to hepatitis B
      m_P_proposed_practice["DBD ECD good", "HBV"] <-
        round(tp_HBV_proposed_practice, 4)
      
      ### to hepatitis C
      m_P_proposed_practice["DBD ECD good", "HCV"] <-
        round(tp_HCV_proposed_practice, 5)
      
      total_trans_prob_DBDECD_good =
        m_P_proposed_practice["DBD ECD good", "HIV"] +
        m_P_proposed_practice["DBD ECD good", "HBV"] +
        m_P_proposed_practice["DBD ECD good", "HCV"]
      
      ### good graft function post kidney transplant. All the remaining patients would move here.
      m_P_proposed_practice["DBD ECD good", "Good graft DBD ECD"] <-
        1 - total_trans_prob_DBDECD_good
      
      
      ## From DBD ECD moderate
      ### to HIV
      m_P_proposed_practice["DBD ECD moderate", "HIV"] <-
        round(tp_HIV_proposed_practice, 7)
      
      ### to hepatitis B
      m_P_proposed_practice["DBD ECD moderate", "HBV"] <-
        round(tp_HBV_proposed_practice, 4)
      
      ### to hepatitis C
      m_P_proposed_practice["DBD ECD moderate", "HCV"] <-
        round(tp_HCV_proposed_practice, 5)
      
      total_trans_prob_DBDECD_moderate =
        m_P_proposed_practice["DBD ECD moderate", "HIV"] +
        m_P_proposed_practice["DBD ECD moderate", "HBV"] +
        m_P_proposed_practice["DBD ECD moderate", "HCV"]
      
      ### moderate graft function post kidney transplant. All the remaining patients would move here.
      m_P_proposed_practice["DBD ECD moderate", "Moderate graft DBD ECD"] <-
        1 - total_trans_prob_DBDECD_moderate
      
      
      ## From DBD ECD poor
      ### to HIV
      m_P_proposed_practice["DBD ECD poor", "HIV"] <-
        round(tp_HIV_proposed_practice, 7)
      
      ### to hepatitis B
      m_P_proposed_practice["DBD ECD poor", "HBV"] <-
        round(tp_HBV_proposed_practice, 4)
      
      ### to hepatitis C
      m_P_proposed_practice["DBD ECD poor", "HCV"] <-
        round(tp_HCV_proposed_practice, 5)
      
      total_trans_prob_DBDECD_poor =
        m_P_proposed_practice["DBD ECD poor", "HIV"] +
        m_P_proposed_practice["DBD ECD poor", "HBV"] +
        m_P_proposed_practice["DBD ECD poor", "HCV"]
      
      ### poor graft function post kidney transplant. All the remaining patients would move here.
      m_P_proposed_practice["DBD ECD poor", "Poor graft DBD ECD"] <-
        1 - total_trans_prob_DBDECD_poor
      
      
      ## From DCD good
      ### to HIV
      m_P_proposed_practice["DCD good", "HIV"] <-
        round(tp_HIV_proposed_practice, 7)
      
      ### to hepatitis B
      m_P_proposed_practice["DCD good", "HBV"] <-
        round(tp_HBV_proposed_practice, 4)
      
      ### to hepatitis C
      m_P_proposed_practice["DCD good", "HCV"] <-
        round(tp_HCV_proposed_practice, 5)
      
      total_trans_prob_DCD_good =
        m_P_proposed_practice["DCD good", "HIV"] +
        m_P_proposed_practice["DCD good", "HBV"] +
        m_P_proposed_practice["DCD good", "HCV"]
      
      ### good graft function post kidney transplant. All the remaining patients would move here.
      m_P_proposed_practice["DCD good", "Good graft DCD"] <-
        1 - total_trans_prob_DCD_good
      
      
      ## From DCD moderate
      ### to HIV
      m_P_proposed_practice["DCD moderate", "HIV"] <-
        round(tp_HIV_proposed_practice, 7)
      
      ### to hepatitis B
      m_P_proposed_practice["DCD moderate", "HBV"] <-
        round(tp_HBV_proposed_practice, 4)
      
      ### to hepatitis C
      m_P_proposed_practice["DCD moderate", "HCV"] <-
        round(tp_HCV_proposed_practice, 5)
      
      total_trans_prob_DCD_moderate =
        m_P_proposed_practice["DCD moderate", "HIV"] +
        m_P_proposed_practice["DCD moderate", "HBV"] +
        m_P_proposed_practice["DCD moderate", "HCV"]
      
      ### moderate graft function post kidney transplant. All the remaining patients would move here.
      m_P_proposed_practice["DCD moderate", "Moderate graft DCD"] <-
        1 - total_trans_prob_DCD_moderate
      
      
      ## From DCD poor
      ### to HIV
      m_P_proposed_practice["DCD poor", "HIV"] <-
        round(tp_HIV_proposed_practice, 7)
      
      ### to hepatitis B
      m_P_proposed_practice["DCD poor", "HBV"] <-
        round(tp_HBV_proposed_practice, 4)
      ### to hepatitis C
      m_P_proposed_practice["DCD poor", "HCV"] <-
        round(tp_HCV_proposed_practice, 5)
      
      total_trans_prob_DCD_poor =
        m_P_proposed_practice["DCD poor", "HIV"] +
        m_P_proposed_practice["DCD poor", "HBV"] +
        m_P_proposed_practice["DCD poor", "HCV"]
      
      ### poor graft function post kidney transplant. All the remaining patients would move here.
      m_P_proposed_practice["DCD poor", "Poor graft DCD"] <-
        1 - total_trans_prob_DCD_poor
      
      
      #3. From good graft DBD SCD
      m_P_proposed_practice["Good graft DBD SCD", "Moderate graft DBD SCD"] <-
        round(tp_gm_DBDSCD, 4)
      m_P_proposed_practice["Good graft DBD SCD", "Poor graft DBD SCD"] <-
        round(tp_gp_DBDSCD, 4)
      m_P_proposed_practice["Good graft DBD SCD", "Death w functioning graft"] <-
        round(tp_gd_DBDSCD, 4)
      
      trans_good_other <-
        m_P_proposed_practice["Good graft DBD SCD", "Moderate graft DBD SCD"] +
        m_P_proposed_practice["Good graft DBD SCD", "Poor graft DBD SCD"] +
        m_P_proposed_practice["Good graft DBD SCD", "Death w functioning graft"]
      
      m_P_proposed_practice["Good graft DBD SCD", "Good graft DBD SCD"] <-
        1 - trans_good_other
      
      
      #4. From moderate graft DBD SCD
      m_P_proposed_practice["Moderate graft DBD SCD", "Poor graft DBD SCD"] <-
        round(tp_mp_DBDSCD, 4)
      m_P_proposed_practice["Moderate graft DBD SCD", "Death w functioning graft"] <-
        round(tp_md_DBDSCD, 4)
      
      trans_moderate_other <-
        m_P_proposed_practice["Moderate graft DBD SCD", "Poor graft DBD SCD"] +
        m_P_proposed_practice["Moderate graft DBD SCD", "Death w functioning graft"]
      
      m_P_proposed_practice["Moderate graft DBD SCD", "Moderate graft DBD SCD"] <-
        1 - trans_moderate_other
      
      
      #5. From poor graft  DBD SCD
      m_P_proposed_practice["Poor graft DBD SCD", "Off waitlist"] <-
        round(tp_graft_failure, 4)
      
      m_P_proposed_practice["Poor graft DBD SCD", "Death after graft failure"] <-
        round(tp_peskd_DBDSCD, 4)
      
      m_P_proposed_practice["Poor graft DBD SCD", "Death w functioning graft"] <-
        round(tp_pd_DBDSCD, 4)
      
      trans_poor_to_other <-
        m_P_proposed_practice["Poor graft DBD SCD", "Off waitlist"] +
        m_P_proposed_practice["Poor graft DBD SCD", "Death after graft failure"] +
        m_P_proposed_practice["Poor graft DBD SCD", "Death w functioning graft"]
      
      m_P_proposed_practice["Poor graft DBD SCD", "Poor graft DBD SCD"] <-
        1 - trans_poor_to_other
      
      
      #6. From good graft DBD ECD
      m_P_proposed_practice["Good graft DBD ECD", "Moderate graft DBD ECD"] <-
        round(tp_gm_DBDECD, 4)
      m_P_proposed_practice["Good graft DBD ECD", "Poor graft DBD ECD"] <-
        round(tp_gp_DBDECD, 4)
      m_P_proposed_practice["Good graft DBD ECD", "Death w functioning graft"] <-
        round(tp_gd_DBDECD, 4)
      
      trans_good_other <-
        m_P_proposed_practice["Good graft DBD ECD", "Moderate graft DBD ECD"] +
        m_P_proposed_practice["Good graft DBD ECD", "Poor graft DBD ECD"] +
        m_P_proposed_practice["Good graft DBD ECD", "Death w functioning graft"]
      
      m_P_proposed_practice["Good graft DBD ECD", "Good graft DBD ECD"] <-
        1 - trans_good_other
      
      
      #7. From moderate graft DBD ECD
      m_P_proposed_practice["Moderate graft DBD ECD", "Poor graft DBD ECD"] <-
        round(tp_mp_DBDECD, 4)
      m_P_proposed_practice["Moderate graft DBD ECD", "Death w functioning graft"] <-
        round(tp_md_DBDECD, 4)
      
      trans_moderate_other <-
        m_P_proposed_practice["Moderate graft DBD ECD", "Poor graft DBD ECD"] +
        m_P_proposed_practice["Moderate graft DBD ECD", "Death w functioning graft"]
      
      m_P_proposed_practice["Moderate graft DBD ECD", "Moderate graft DBD ECD"] <-
        1 - trans_moderate_other
      
      
      #8. From poor graft  DBD ECD
      m_P_proposed_practice["Poor graft DBD ECD", "Off waitlist"] <-
        round(tp_graft_failure, 4)
      
      m_P_proposed_practice["Poor graft DBD ECD", "Death after graft failure"] <-
        round(tp_peskd_DBDECD, 4)
      
      m_P_proposed_practice["Poor graft DBD ECD", "Death w functioning graft"] <-
        round(tp_pd_DBDECD, 4)
      
      trans_poor_to_other <-
        m_P_proposed_practice["Poor graft DBD ECD", "Off waitlist"] +
        m_P_proposed_practice["Poor graft DBD ECD", "Death after graft failure"] +
        m_P_proposed_practice["Poor graft DBD ECD", "Death w functioning graft"]
      
      m_P_proposed_practice["Poor graft DBD ECD", "Poor graft DBD ECD"] <-
        1 - trans_poor_to_other
      
      
      #9. From good graft DCD
      m_P_proposed_practice["Good graft DCD", "Moderate graft DCD"] <-
        round(tp_gm_DCD, 4)
      m_P_proposed_practice["Good graft DCD", "Poor graft DCD"] <-
        round(tp_gp_DCD, 4)
      m_P_proposed_practice["Good graft DCD", "Death w functioning graft"] <-
        round(tp_gd_DCD, 4)
      
      trans_good_other <-
        m_P_proposed_practice["Good graft DCD", "Moderate graft DCD"] +
        m_P_proposed_practice["Good graft DCD", "Poor graft DCD"] +
        m_P_proposed_practice["Good graft DCD", "Death w functioning graft"]
      
      m_P_proposed_practice["Good graft DCD", "Good graft DCD"] <-
        1 - trans_good_other
      
      
      #10. From moderate graft DCD
      m_P_proposed_practice["Moderate graft DCD", "Poor graft DCD"] <-
        round(tp_mp_DCD, 4)
      m_P_proposed_practice["Moderate graft DCD", "Death w functioning graft"] <-
        round(tp_md_DCD, 4)
      
      trans_moderate_other <-
        m_P_proposed_practice["Moderate graft DCD", "Poor graft DCD"] +
        m_P_proposed_practice["Moderate graft DCD", "Death w functioning graft"]
      
      m_P_proposed_practice["Moderate graft DCD", "Moderate graft DCD"] <-
        1 - trans_moderate_other
      
      
      #11. From poor graft  DCD
      m_P_proposed_practice["Poor graft DCD", "Off waitlist"] <-
        round(tp_graft_failure, 4)
      
      m_P_proposed_practice["Poor graft DCD", "Death after graft failure"] <-
        round(tp_peskd_DCD, 4)
      
      m_P_proposed_practice["Poor graft DCD", "Death w functioning graft"] <-
        round(tp_pd_DCD, 4)
      
      trans_poor_to_other <-
        m_P_proposed_practice["Poor graft DCD", "Off waitlist"] +
        m_P_proposed_practice["Poor graft DCD", "Death after graft failure"] +
        m_P_proposed_practice["Poor graft DCD", "Death w functioning graft"]
      
      m_P_proposed_practice["Poor graft DCD", "Poor graft DCD"] <-
        1 - trans_poor_to_other
      
      
      #12. From temporary off-waitlist
      ## Transition to death on dialysis
      m_P_proposed_practice["Off waitlist", "Death off waitlist"] <-
        n_death_off_waitlist
      
      ## Transition back to the waitlist
      m_P_proposed_practice["Off waitlist", "On waitlist"] <-
        round(tp_back_on_waitlist, 3)
      
      ## Calculating the remaining probability after accounting for death and transition back to the waitlist
      total_trans_prob_off_waitlist <-
        round(m_P_proposed_practice["Off waitlist", "Death off waitlist"] + (m_P_proposed_practice["Off waitlist", "On waitlist"]), 3)
      
      m_P_proposed_practice["Off waitlist", "Off waitlist"] <-
        
        1 - total_trans_prob_off_waitlist
      
      #13. From HIV
      ## Death with functioning graft
      m_P_proposed_practice["HIV", "Death w functioning graft"] <-
        n_death_functioning_graft
      
      
      ## people who remain in HIV
      m_P_proposed_practice["HIV", "HIV"] <-
        1 - round(m_P_proposed_practice["HIV", "Death w functioning graft"], 3)
      
      
      #14. From HBV
      ## from HBV to death from other causes
      m_P_proposed_practice["HBV", "Death w functioning graft"] <-
        n_death_functioning_graft
      
      ## HBV to compensated cirrhosis
      m_P_proposed_practice["HBV", "Hep B Comp cirr"] <-
        round(tp_chb_cc_hepB, 5)
      
      ## HBV to spontaneous clearance
      m_P_proposed_practice["HBV", "Spon clearance"] <-
        round(tp_chb_sAgloss_hepB, 4)
      
      ## HBV to hepatocellular carcinoma
      m_P_proposed_practice["HBV", "Hep B HCC"] <- round(tp_chb_hcc, 7)
      
      trans_HBV_other <-
        m_P_proposed_practice["HBV", "Death w functioning graft"] +
        m_P_proposed_practice["HBV", "Hep B Comp cirr"] +
        m_P_proposed_practice["HBV", "Spon clearance"] +
        m_P_proposed_practice["HBV", "Hep B HCC"]
      
      m_P_proposed_practice["HBV", "HBV"] <-
        1 - trans_HBV_other
      
      
      #15. From HCV
      ## From HCV to death from other causes
      m_P_proposed_practice["HCV", "Death w functioning graft"] <-
        n_death_functioning_graft
      
      ## from HCV to compensated cirrhosis
      m_P_proposed_practice["HCV", "Hep C comp cirr"] <-
        round(tp_chc_cc_hepC, 4)
      
      ## from HCV to sustained virological response
      m_P_proposed_practice["HCV", "SVR"] <- tp_SVR
      
      trans_hcv_other <-
        m_P_proposed_practice["HCV", "Death w functioning graft"] +
        m_P_proposed_practice["HCV", "Hep C comp cirr"] +
        m_P_proposed_practice["HCV", "SVR"]
      
      ## people who continue to remain in HCV
      m_P_proposed_practice["HCV", "HCV"] <-
        1 - trans_hcv_other
      
      
      
      #16. From compensated cirrhosis Hep B
      ## From compensated cirrhosis to death from other causes
      m_P_proposed_practice["Hep B Comp cirr", "Death w functioning graft"] <-
        n_death_functioning_graft
      
      ## from compensated cirrhosis to death due to end stage liver disease
      m_P_proposed_practice["Hep B Comp cirr", "Death end stage liver"] <-
        round(tp_death_cc_hepB, 5)
      
      ## from compensated cirrhosis to decompensated cirrhosis
      m_P_proposed_practice["Hep B Comp cirr", "Hep B Decomp cirr"] <-
        round(tp_cc_dc_hepB, 4)
      
      ## from compensated cirrhosis to hepatocellular carcinoma
      m_P_proposed_practice["Hep B Comp cirr", "Hep B HCC"] <-
        round(tp_cc_hcc_hepB, 4)
      
      trans_comp_hepB <-
        m_P_proposed_practice["Hep B Comp cirr", "Death w functioning graft"] +
        m_P_proposed_practice["Hep B Comp cirr", "Death end stage liver"] +
        m_P_proposed_practice["Hep B Comp cirr", "Hep B Decomp cirr"] +
        m_P_proposed_practice["Hep B Comp cirr", "Hep B HCC"]
      
      m_P_proposed_practice["Hep B Comp cirr", "Hep B Comp cirr"] <-
        1 - trans_comp_hepB
      
      
      
      #17. From compensated cirrhosis Hep C
      ## From compensated cirrhosis to death from other causes
      m_P_proposed_practice["Hep C comp cirr", "Death w functioning graft"] <-
        n_death_functioning_graft
      
      ## from compensated cirrhosis to decompensated cirrhosis
      m_P_proposed_practice["Hep C comp cirr", "Hep C Decomp cirr"] <-
        round(tp_cc_dc_hepC, 4)
      
      ## from compensated cirrhosis to hepatocellular carcinoma
      m_P_proposed_practice["Hep C comp cirr", "Hep C HCC"] <-
        round(tp_cc_hcc_hepC, 4)
      
      trans_comp_hepC <-
        m_P_proposed_practice["Hep C comp cirr", "Death w functioning graft"] +
        m_P_proposed_practice["Hep C comp cirr", "Hep C Decomp cirr"] +
        m_P_proposed_practice["Hep C comp cirr", "Hep C HCC"]
      
      m_P_proposed_practice["Hep C comp cirr", "Hep C comp cirr"] <-
        1 - trans_comp_hepC
      
      
      #18. From decompensated cirrhosis Hep B
      ## From decompensated cirrhosis to death from other causes
      m_P_proposed_practice["Hep B Decomp cirr", "Death w functioning graft"] <-
        n_death_functioning_graft
      
      ## from decompemnsated cirrhosis to death due to end stage liver disease
      m_P_proposed_practice["Hep B Decomp cirr", "Death end stage liver"] <-
        round(tp_death_dc_hepB, 4)
      
      ## from decompensated cirrhosis to hepatocellular carcinoma
      m_P_proposed_practice["Hep B Decomp cirr", "Hep B HCC"] <-
        round(tp_dc_hcc_hepB, 4)
      
      ## from deoompensated cirrhosis to liver transplant
      m_P_proposed_practice["Hep B Decomp cirr", "Liver transplant 3"] <-
        round(tp_dc_lt_hepB, 4)
      
      trans_decom_hepB <-
        m_P_proposed_practice["Hep B Decomp cirr", "Death w functioning graft"] +
        m_P_proposed_practice["Hep B Decomp cirr", "Death end stage liver"] +
        m_P_proposed_practice["Hep B Decomp cirr", "Hep B HCC"] +
        m_P_proposed_practice["Hep B Decomp cirr", "Liver transplant 3"]
      
      ## people who continue to remain in decompensated cirrhosis
      m_P_proposed_practice["Hep B Decomp cirr", "Hep B Decomp cirr"] <-
        1 - trans_decom_hepB
      
      
      
      #19. From decompensated cirrhosis Hep C
      ## From decompensated cirrhosis to death from other causes
      m_P_proposed_practice["Hep C Decomp cirr", "Death w functioning graft"] <-
        n_death_functioning_graft
      
      ## from decompemnsated cirrhosis to death due to end stage liver disease
      m_P_proposed_practice["Hep C Decomp cirr", "Death end stage liver"] <-
        round(tp_death_dc_hepC, 4)
      
      ## from decompensated cirrhosis to hepatocellular carcinoma
      m_P_proposed_practice["Hep C Decomp cirr", "Hep C HCC"] <-
        round(tp_dc_hcc_hepC, 4)
      
      ## from decompensated cirrhosis to liver transplant
      m_P_proposed_practice["Hep C Decomp cirr", "Liver transplant 3"] <-
        round(tp_dc_lt_hepC, 4)
      
      trans_decom_hepC <-
        m_P_proposed_practice["Hep C Decomp cirr", "Death w functioning graft"] +
        m_P_proposed_practice["Hep C Decomp cirr", "Death end stage liver"] +
        m_P_proposed_practice["Hep C Decomp cirr", "Hep C HCC"] +
        m_P_proposed_practice["Hep C Decomp cirr", "Liver transplant 3"]
      
      m_P_proposed_practice["Hep C Decomp cirr", "Hep C Decomp cirr"] <-
        1 - trans_decom_hepC
      
      
      
      #20. From hepatocellular carcinoma Hep B
      ## from hepatocellular carcinoma to death from other causes
      m_P_proposed_practice["Hep B HCC", "Death w functioning graft"] <-
        n_death_functioning_graft
      
      ## from hepatocellular carcinoma to death due to end stage liver disease
      m_P_proposed_practice["Hep B HCC", "Death end stage liver"] <-
        round(tp_death_hcc_hepB, 4)
      
      ## from hepatocellular carcinoma to liver transplant
      m_P_proposed_practice["Hep B HCC", "Liver transplant 3"] <-
        round(tp_hcc_lt_hepB, 4)
      
      trans_hcc_hepB <-
        m_P_proposed_practice["Hep B HCC", "Death w functioning graft"] +
        m_P_proposed_practice["Hep B HCC", "Death end stage liver"] +
        m_P_proposed_practice["Hep B HCC", "Liver transplant 3"]
      
      m_P_proposed_practice["Hep B HCC", "Hep B HCC"] <-
        1 - trans_hcc_hepB
      
      
      
      #21. From hepatocellular carcinoma Hep C
      ## from hepatocellular carcinoma to death from other causes
      m_P_proposed_practice["Hep C HCC", "Death w functioning graft"] <-
        n_death_functioning_graft
      
      ## from hepatocellular carcinoma to death due to end stage liver disease
      m_P_proposed_practice["Hep C HCC", "Death end stage liver"] <-
        round(tp_death_hcc_hepC, 4)
      
      ## from hepatocellular carcinoma to liver transplant
      m_P_proposed_practice["Hep C HCC", "Liver transplant 3"] <-
        round(tp_hcc_lt_hepC, 4)
      
      trans_hcc_hepC <-
        m_P_proposed_practice["Hep C HCC", "Death w functioning graft"] +
        m_P_proposed_practice["Hep C HCC", "Death end stage liver"] +
        m_P_proposed_practice["Hep C HCC", "Liver transplant 3"]
      
      m_P_proposed_practice["Hep C HCC", "Hep C HCC"] <-
        1 - trans_hcc_hepC
      
      
      
      #22. From spontaneous clearance
      ## from spon clearance to death from other causes
      m_P_proposed_practice["Spon clearance", "Death w functioning graft"] <-
        n_death_functioning_graft
      
      trans_sponclear <-
        m_P_proposed_practice["Spon clearance", "Death w functioning graft"]
      
      m_P_proposed_practice["Spon clearance", "Spon clearance"] <-
        1 - trans_sponclear
      
      
      
      #23. From SVR
      ## from SVR to death from other causes
      m_P_proposed_practice["SVR", "Death w functioning graft"] <-
        n_death_functioning_graft
      
      trans_svr <-
        m_P_proposed_practice["SVR", "Death w functioning graft"]
      
      m_P_proposed_practice["SVR", "SVR"] <- 1 - trans_svr
      
      
      
      #24. From liver transplant
      ## Liver transplant year 1: 3 months
      m_P_proposed_practice["Liver transplant 3", "Death end stage liver"] <-
        round(tp_death_LT, 4)
      
      total_outgoing <-
        m_P_proposed_practice["Liver transplant 3", "Death end stage liver"]
      
      m_P_proposed_practice["Liver transplant 3", "Liver transplant 6"] <-
        1 - total_outgoing
      
      
      #25. from LT 6 to death
      m_P_proposed_practice["Liver transplant 6", "Death end stage liver"] <-
        round(tp_death_LT, 4)
      
      total_outgoing <-
        m_P_proposed_practice["Liver transplant 6", "Death end stage liver"]
      
      
      m_P_proposed_practice["Liver transplant 6", "Liver transplant 9"] <-
        1 - total_outgoing
      
      
      
      #26. from LT 9 to death
      m_P_proposed_practice["Liver transplant 9", "Death end stage liver"] <-
        round(tp_death_LT, 4)
      
      total_outgoing <-
        m_P_proposed_practice["Liver transplant 9", "Death end stage liver"]
      
      m_P_proposed_practice["Liver transplant 9", "Liver transplant 12"] <-
        1 - total_outgoing
      
      
      
      #27. from LT 12 to death
      m_P_proposed_practice["Liver transplant 12", "Death end stage liver"] <-
        round(tp_death_LT, 4)
      
      total_outgoing <-
        m_P_proposed_practice["Liver transplant 12", "Death end stage liver"]
      
      m_P_proposed_practice["Liver transplant 12", "Liver transplant yr 2"] <-
        1 - total_outgoing
      
      
      
      #28. Liver transplant Year 2+
      # Transition from "Liver transplant yr 2" to "Death end stage liver"
      m_P_proposed_practice["Liver transplant yr 2", "Death end stage liver"] <-
        round(tp_death_LT, 4)
      
      trans_lt2 <-
        m_P_proposed_practice["Liver transplant yr 2", "Death end stage liver"]
      
      m_P_proposed_practice["Liver transplant yr 2", "Liver transplant yr 2"] <-
        1 - trans_lt2
      
      
      
      #30. Death
      m_P_proposed_practice["Death on waitlist", "Death on waitlist"] <- 1
      
      m_P_proposed_practice["Death off waitlist", "Death off waitlist"] <-
        1
      
      m_P_proposed_practice["Death w functioning graft", "Death w functioning graft"] <-
        1
      
      m_P_proposed_practice["Death after graft failure", "Death after graft failure"] <-
        1
      
      m_P_proposed_practice["Death end stage liver", "Death end stage liver"] <-
        1
      
      
      
      #iterative solution of time independent cohort model
      for (t in 1:n_cycles) {
        # Current practice
        m_M_current_practice[t + 1,] <-
          m_M_current_practice[t,] %*% m_P_current_practice
        
        
        # proposed practice
        m_M_proposed_practice[t + 1,] <-
          m_M_proposed_practice[t, ] %*% m_P_proposed_practice
        
      }
      
      # Create aggregated traces
      m_M_current_practice_sum <-
        cbind(Waitlist = m_M_current_practice[, "On waitlist"],
              DBD_SCD_good = m_M_current_practice[, "DBD SCD good"],
          DBD_SCD_moderate = m_M_current_practice[, "DBD SCD moderate"],
          DBD_SCD_poor = m_M_current_practice[, "DBD SCD poor"],
          DBD_ECD_good =  m_M_current_practice[, "DBD ECD good"],
          DBD_ECD_moderate = m_M_current_practice[, "DBD ECD moderate"],
          DBD_ECD_poor = m_M_current_practice[, "DBD ECD poor"],
          DCD_good = m_M_current_practice[, "DCD good"],
          DCD_moderate = m_M_current_practice[, "DCD moderate"],
          DCD_poor = m_M_current_practice[, "DCD poor"],
          gg_DBD_SCD =  m_M_current_practice[, "Good graft DBD SCD"],
          mg_DBD_SCD =  m_M_current_practice[, "Moderate graft DBD SCD"],
          pg_DBD_SCD =  m_M_current_practice[, "Poor graft DBD SCD"],
          gg_DBD_ECD =  m_M_current_practice[, "Good graft DBD ECD"],
          mg_DBD_ECD =  m_M_current_practice[, "Moderate graft DBD ECD"],
          pg_DBD_ECD =  m_M_current_practice[, "Poor graft DBD ECD"],
          gg_DCD =  m_M_current_practice[, "Good graft DCD"],
          mg_DCD =  m_M_current_practice[, "Moderate graft DCD"],
          pg_DCD =  m_M_current_practice[, "Poor graft DCD"],
          Off_waitlist = m_M_current_practice[, "Off waitlist"],
          Good_graft = m_M_current_practice[, "Good graft DCD"] +
            m_M_current_practice[, "Good graft DBD SCD"] +
            m_M_current_practice[, "Good graft DBD ECD"],
          Moderate_graft = m_M_current_practice[, "Moderate graft DCD"] +
            m_M_current_practice[, "Moderate graft DBD SCD"] +
            m_M_current_practice[, "Moderate graft DBD ECD"],
          Poor_graft = m_M_current_practice[, "Poor graft DCD"] +
            m_M_current_practice[, "Poor graft DBD SCD"] +
            m_M_current_practice[, "Poor graft DBD ECD"],
          HIV = m_M_current_practice[, "HIV"],
          HBV = m_M_current_practice[, "HBV"],
          HCV = m_M_current_practice[, "HCV"],
          HepB_Comp_cirr = m_M_current_practice[, "Hep B Comp cirr"],
          HepC_Comp_cirr = m_M_current_practice[, "Hep C comp cirr"],
          HepB_Decomp_cirr = m_M_current_practice[, "Hep B Decomp cirr"],
          HepC_Decomp_cirr = m_M_current_practice[, "Hep C Decomp cirr"],
          HepB_HCC = m_M_current_practice[, "Hep B HCC"],
          HepC_HCC = m_M_current_practice[, "Hep C HCC"],
          Spon_clear = m_M_current_practice[, "Spon clearance"],
          SVR = m_M_current_practice[, "SVR"],
          Liver_trans_1yr = m_M_current_practice[, "Liver transplant 3"] +
            m_M_current_practice[, "Liver transplant 6"] +
            m_M_current_practice[, "Liver transplant 9"] +
            m_M_current_practice[, "Liver transplant 12"],
          Liver_trans_2yr = m_M_current_practice[, "Liver transplant yr 2"],
          Death_waitlist = m_M_current_practice[, "Death on waitlist"],
          Death_off_waitlist = m_M_current_practice[, "Death off waitlist"],
          Death_after_graft_failure = m_M_current_practice[, "Death after graft failure"],
          Death_w_functioning_graft = m_M_current_practice[, "Death w functioning graft"],
          Death_liver = m_M_current_practice[, "Death end stage liver"]
        )
      
      m_M_proposed_practice_sum <-
        cbind(
          Waitlist = m_M_proposed_practice[, "On waitlist"],
          DBD_SCD_good = m_M_proposed_practice[, "DBD SCD good"],
          DBD_SCD_moderate = m_M_proposed_practice[, "DBD SCD moderate"],
          DBD_SCD_poor = m_M_proposed_practice[, "DBD SCD poor"],
          DBD_ECD_good =  m_M_proposed_practice[, "DBD ECD good"],
          DBD_ECD_moderate = m_M_proposed_practice[, "DBD ECD moderate"],
          DBD_ECD_poor = m_M_proposed_practice[, "DBD ECD poor"],
          DCD_good = m_M_proposed_practice[, "DCD good"],
          DCD_moderate = m_M_proposed_practice[, "DCD moderate"],
          DCD_poor = m_M_proposed_practice[, "DCD poor"],
          gg_DBD_SCD =  m_M_proposed_practice[, "Good graft DBD SCD"],
          mg_DBD_SCD =  m_M_proposed_practice[, "Moderate graft DBD SCD"],
          pg_DBD_SCD =  m_M_proposed_practice[, "Poor graft DBD SCD"],
          gg_DBD_ECD =  m_M_proposed_practice[, "Good graft DBD ECD"],
          mg_DBD_ECD =  m_M_proposed_practice[, "Moderate graft DBD ECD"],
          pg_DBD_ECD =  m_M_proposed_practice[, "Poor graft DBD ECD"],
          gg_DCD =  m_M_proposed_practice[, "Good graft DCD"],
          mg_DCD =  m_M_proposed_practice[, "Moderate graft DCD"],
          pg_DCD =  m_M_proposed_practice[, "Poor graft DCD"],
          Off_waitlist = m_M_proposed_practice[, "Off waitlist"],
          Good_graft = m_M_proposed_practice[, "Good graft DCD"] +
            m_M_proposed_practice[, "Good graft DBD SCD"] +
            m_M_proposed_practice[, "Good graft DBD ECD"],
          Moderate_graft = m_M_proposed_practice[, "Moderate graft DCD"] +
            m_M_proposed_practice[, "Moderate graft DBD SCD"] +
            m_M_proposed_practice[, "Moderate graft DBD ECD"],
          Poor_graft = m_M_proposed_practice[, "Poor graft DCD"] +
            m_M_proposed_practice[, "Poor graft DBD SCD"] +
            m_M_proposed_practice[, "Poor graft DBD ECD"],
          HIV = m_M_proposed_practice[, "HIV"],
          HBV = m_M_proposed_practice[, "HBV"],
          HCV = m_M_proposed_practice[, "HCV"],
          HepB_Comp_cirr = m_M_proposed_practice[, "Hep B Comp cirr"],
          HepC_Comp_cirr = m_M_proposed_practice[, "Hep C comp cirr"],
          HepB_Decomp_cirr = m_M_proposed_practice[, "Hep B Decomp cirr"],
          HepC_Decomp_cirr = m_M_proposed_practice[, "Hep C Decomp cirr"],
          HepB_HCC = m_M_proposed_practice[, "Hep B HCC"],
          HepC_HCC = m_M_proposed_practice[, "Hep C HCC"],
          Spon_clear = m_M_proposed_practice[, "Spon clearance"],
          SVR = m_M_proposed_practice[, "SVR"],
          Liver_trans_1yr = m_M_proposed_practice[, "Liver transplant 3"] +
            m_M_proposed_practice[, "Liver transplant 6"] +
            m_M_proposed_practice[, "Liver transplant 9"] +
            m_M_proposed_practice[, "Liver transplant 12"],
          Liver_trans_2yr = m_M_proposed_practice[, "Liver transplant yr 2"],
          Death_waitlist = m_M_proposed_practice[, "Death on waitlist"],
          Death_off_waitlist = m_M_proposed_practice[, "Death off waitlist"],
          Death_after_graft_failure = m_M_proposed_practice[, "Death after graft failure"],
          Death_w_functioning_graft = m_M_proposed_practice[, "Death w functioning graft"],
          Death_liver = m_M_proposed_practice[, "Death end stage liver"]
        )


      ## Strategy names
      v_names_str <- c("Current clinical practice", "Shift in clinical practice") 
      n_str <- length(v_names_str)
      
      ## Store the cohort traces in a list
      l_m_M <- list(m_M_current_practice_sum,
                    m_M_proposed_practice_sum)
      
      names(l_m_M) <- v_names_str
      
      ###################### RETURN OUTPUT ######################
      return(
        list(current_practice_sum = m_M_current_practice_sum, proposed_practice_sum = m_M_proposed_practice_sum,
             current_practice = m_M_current_practice, proposed_practice = m_M_proposed_practice,
             current_practice_p = m_P_current_practice, proposed_practice_p = m_P_proposed_practice)
      )
      
    }
)
}

```

# Calculate CE outcome
```{r}
calculate_ce_out <-
  function(l_params_all, n_wtp = 50000) {
    with(as.list(l_params_all),
         {
           #### Run Markov Model ####
           model_results <- decision_model(l_params_all = l_params_all)
           m_M_current_practice_sum <- model_results$current_practice_sum
           m_M_proposed_practice_sum <- model_results$proposed_practice_sum
           m_M_current_practice <- model_results$current_practice
           m_M_proposed_practice <- model_results$proposed_practice
           m_P_current_practice <- model_results$current_practice_p
           m_P_proposed_practice <- model_results$proposed_practice_p
           
           ## Strategy names
           v_names_str <- c("Current clinical practice", "Shift in clinical practice")
           n_str <- length(v_names_str)
           
           
           #### State Rewards ####
           v_u <- c(
             Waitlist = u_on_waitlist_dialysis,
             DBD_SCD_good = u_transplantation_gg_function,
             DBD_SCD_moderate = u_transplantation_mg_function,
             DBD_SCD_poor = u_transplantation_pg_function,
             DBD_ECD_good = u_transplantation_gg_function,
             DBD_ECD_moderate = u_transplantation_mg_function,
             DBD_ECD_poor = u_transplantation_pg_function,
             DCD_good = u_transplantation_gg_function,
             DCD_moderate = u_transplantation_mg_function,
             DCD_poor = u_transplantation_pg_function,
             gg_DBD_SCD = 0,
             mg_DBD_SCD = 0,
             pg_DBD_SCD = 0,
             gg_DBD_ECD = 0,
             mg_DBD_ECD = 0,
             pg_DBD_ECD = 0,
             gg_DCD = 0,
             mg_DCD = 0,
             pg_DCD = 0,
             Off_waitlist = u_on_waitlist_dialysis,
             Good_graft = u_transplantation_gg_function,
             Moderate_graft = u_transplantation_mg_function,
             Poor_graft = u_transplantation_pg_function,
             HIV = u_HIV,
             HBV = u_CHB_hepB,
             HCV = u_CHC_hepC,
             HepB_Comp_cirr = u_CC_hepB,
             HepC_Comp_cirr = u_CC_hepC,
             HepB_Decomp_cirr = u_DC_hepB,
             HepC_Decomp_cirr = u_DC_hepC,
             HepB_HCC = u_HCC_hepB,
             HepC_HCC = u_HCC_hepC,
             Spon_clear = u_sag_clearance,
             SVR = u_SVR_hepC,
             Liver_trans_1yr = u_liver_transplant_year_1,
             Liver_trans_2yr = u_liver_transplant_year_2,
             Death_waitlist = 0,
             Death_off_waitlist = 0,
             Death_after_graft_failure = 0,
             Death_w_functioning_graft = 0,
             Death_liver = 0
           ) * cycle_length
           
           
           waitlist_Cost <-
             sum((pro_HD * c_in_centre_haemodialysis),
                 (pro_PD * c_peritoneal_dialysis),
                 (pro_HHD * c_home_haemodialysis),
                 c_work_up_transplant_waitlist
             ) * cycle_length
           
           off_Waitlist_cost <- sum((pro_HD * c_in_centre_haemodialysis),
                                    (pro_PD * c_peritoneal_dialysis),
                                    (pro_HHD * c_home_haemodialysis)
           ) * cycle_length
           
           
           v_c <-
             c(
               Waitlist = waitlist_Cost,
               DBD_SCD_good = c_kidney_transplant_year_1,
               DBD_SCD_moderate = c_kidney_transplant_year_1,
               DBD_SCD_poor = c_kidney_transplant_year_1,
               DBD_ECD_good = c_kidney_transplant_year_1,
               DBD_ECD_moderate = c_kidney_transplant_year_1,
               DBD_ECD_poor = c_kidney_transplant_year_1,
               DCD_good = c_kidney_transplant_year_1,
               DCD_moderate = c_kidney_transplant_year_1,
               DCD_poor = c_kidney_transplant_year_1,
               gg_DBD_SCD = 0,
               mg_DBD_SCD = 0,
               pg_DBD_SCD = 0,
               gg_DBD_ECD = 0,
               mg_DBD_ECD = 0,
               pg_DBD_ECD = 0,
               gg_DCD = 0,
               mg_DCD = 0,
               pg_DCD = 0,
               Off_waitlist = off_Waitlist_cost,
               Good_graft = c_good_graft_post_transplant * cycle_length,
               Moderate_graft = c_moderate_graft_post_transplant * cycle_length,
               Poor_graft = c_poor_graft_post_transplant * cycle_length,
               HIV = (c_remaining_HIV) * cycle_length,
               HBV = c_chronic_hepB * cycle_length,
               HCV = c_chronic_HCV * cycle_length,
               HepB_Comp_cirr = c_compensated_cirrhosis_hepB * cycle_length,
               HepC_Comp_cirr = c_compensated_cirrhosis_hepC * cycle_length,
               HepB_Decomp_cirr = c_decompensated_cirrhosis_hepB * cycle_length,
               HepC_Decomp_cirr = c_decompensated_cirrhosis_hepC * cycle_length,
               HepB_HCC = c_hepatocellular_carcinoma_hepB * cycle_length,
               HepC_HCC = c_hepatocellular_carcinoma_hepC * cycle_length,
               Spon_clear = c_chronic_hepB * cycle_length,
               SVR =  0,
               Liver_trans_1yr = c_liver_transplant_year_1 * cycle_length,
               Liver_trans_2yr = c_liver_transplant_year_2 * cycle_length,
               Death_waitlist = 0,
               Death_off_waitlist = 0,
               Death_after_graft_failure = 0,
               Death_w_functioning_graft = 0,
               Death_liver = 0
             )
           
           c_dbd_scd_good <-
             (
               sum(
                 c_kidney_transplant_year_1,
                 c_follow_up,
                 c_diagosis_proposed_policy,
                 (c_proph_hepB)
               ) * round(
                 per_effect_increased_risk_behaviours * (1 - pro_DBDSCD_mg - pro_DBDSCD_pg - tp_graft_failure),
                 4
               )
             )
           
           c_dbd_scd_moderate <-
             (
               sum(
                 c_kidney_transplant_year_1,
                 c_follow_up,
                 c_diagosis_proposed_policy,
                 (c_proph_hepB)
               ) *  round(pro_DBDSCD_mg * per_effect_increased_risk_behaviours, 4)
             )
           
           c_dbd_scd_poor <-
             (
               sum(
                 c_kidney_transplant_year_1,
                 c_follow_up,
                 c_diagosis_proposed_policy,
                 (c_proph_hepB)
                 
               ) *
                 round(pro_DBDSCD_pg * per_effect_increased_risk_behaviours, 4)
             )
           
           
           c_treating_hepC <- sum(c_diagnosing_HCV, mean(
             c(
               c_treating_mild_moderate_chronic_hepC_gen1_2,
               c_treating_mild_moderate_chronic_hepC_gen3
             )
           ))
           
           
           
           c_kt_hcv <- sum(
             c_kidney_transplant_year_1,
             c_diagnosing_HCV,
             c_treating_hepC,
             c_follow_up
           )
           
           
           ######## Transition rewards ###########
           
           # Initialize vectors for base and additional costs
           v_cost_cp <- numeric(n_cycles + 1)
           v_qalys_cp <- numeric(n_cycles + 1)
           
           # Calculate base costs from state occupancies for both practices
           for (i in 1:(n_cycles + 1)) {
             v_cost_cp[i] <- sum(m_M_current_practice_sum[i, ] * v_c)
             v_qalys_cp[i] <- sum(m_M_current_practice_sum[i, ] * v_u)
           }
           
           # Current practice
           additional_costs_cp <- numeric(n_cycles + 1)
           
           # Calculate additional costs for current practice
           for (i in 2:(n_cycles + 1)) {
             additional_costs_cp[i] <- 0  # Reset to 0 for each cycle
             
             # hbv
             for (state in c(
               "DBD SCD good",
               "DBD SCD moderate",
               "DBD SCD poor",
               "DBD ECD good",
               "DBD ECD moderate",
               "DBD ECD poor",
               "DCD good",
               "DCD moderate",
               "DCD poor"
             )) {
               transition_to_hbv <-
                 m_M_current_practice[i - 1, state] * m_P_current_practice[state, "HBV"]
               additional_costs_cp[i] <-
                 additional_costs_cp[i] + transition_to_hbv * c_diagnosing_hepB
             }
             
             # hiv
             for (state in c(
               "DBD SCD good",
               "DBD SCD moderate",
               "DBD SCD poor",
               "DBD ECD good",
               "DBD ECD moderate",
               "DBD ECD poor",
               "DCD good",
               "DCD moderate",
               "DCD poor"
             )) {
               transition_to_hiv <-
                 m_M_current_practice[i - 1, state] * m_P_current_practice[state, "HIV"]
               additional_costs_cp[i] <-
                 additional_costs_cp[i] + transition_to_hiv * c_diagnosing_HIV
             }
             
             # hcv
             for (state in c(
               "DBD SCD good",
               "DBD SCD moderate",
               "DBD SCD poor",
               "DBD ECD good",
               "DBD ECD moderate",
               "DBD ECD poor",
               "DCD good",
               "DCD moderate",
               "DCD poor"
             )) {
               transition_to_hcv <-
                 m_M_current_practice[i - 1, state] * m_P_current_practice[state, "HCV"]
               additional_costs_cp[i] <-
                 additional_costs_cp[i] + transition_to_hcv * c_treating_hepC
             }
             
             # back to waitlist
             
             transition_to_waitlist <-
               m_M_current_practice[i - 1, "Off waitlist"] * m_P_current_practice["Off waitlist", "On waitlist"]
             additional_costs_cp[i] <-
               additional_costs_cp[i] + transition_to_waitlist * c_work_up_transplant_waitlist
             
             # to compensated cirr
             transtion_to_comp_cirr_hbv <-
               m_M_current_practice[i - 1, "HBV"] * m_P_current_practice["HBV", "Hep B Comp cirr"]
             additional_costs_cp[i] <-
               additional_costs_cp[i] + transtion_to_comp_cirr_hbv * c_one_off_transition_to_CC
             
             transtion_to_comp_cirr_hcv <-
               m_M_current_practice[i - 1, "HCV"] * m_P_current_practice["HCV", "Hep C comp cirr"]
             additional_costs_cp[i] <-
               additional_costs_cp[i] + transtion_to_comp_cirr_hcv * c_one_off_transition_to_CC
             
             # to hcc
             transition_to_hcc_hbv <-
               m_M_current_practice[i - 1, "HBV"] * m_P_current_practice["HBV", "Hep B HCC"]
             additional_costs_cp[i] <-
               additional_costs_cp[i] + transition_to_hcc_hbv * c_one_off_transition_to_hcc
             
             
             transition_to_hcc_hbv_comp <-
               m_M_current_practice[i - 1, "Hep B Comp cirr"] * m_P_current_practice["Hep B Comp cirr", "Hep B HCC"]
             additional_costs_cp[i] <-
               additional_costs_cp[i] + transition_to_hcc_hbv_comp * c_one_off_transition_to_hcc
             
             transition_to_hcc_hcv_comp <-
               m_M_current_practice[i - 1, "Hep C comp cirr"] * m_P_current_practice["Hep C comp cirr", "Hep C HCC"]
             additional_costs_cp[i] <-
               additional_costs_cp[i] + transition_to_hcc_hcv_comp * c_one_off_transition_to_hcc
             
             transition_to_hcc_hbv_decomp <-
               m_M_current_practice[i - 1, "Hep B Decomp cirr"] * m_P_current_practice["Hep B Decomp cirr", "Hep B HCC"]
             additional_costs_cp[i] <-
               additional_costs_cp[i] + transition_to_hcc_hbv_decomp * c_one_off_transition_to_hcc
             
             transition_to_hcc_hcv_decomp <-
               m_M_current_practice[i - 1, "Hep C Decomp cirr"] * m_P_current_practice["Hep C Decomp cirr", "Hep C HCC"]
             additional_costs_cp[i] <-
               additional_costs_cp[i] + transition_to_hcc_hcv_decomp * c_one_off_transition_to_hcc
             
             # to SVR
             transition_to_SVR <-
               m_M_current_practice[i - 1, "HCV"] * m_P_current_practice["HCV", "SVR"]
             additional_costs_cp[i] <-
               additional_costs_cp[i] + transition_to_SVR * c_SVR_hepC
             
             
             v_cost_cp[i] <- v_cost_cp[i] + additional_costs_cp[i]
           }
           
           ### Transition qalys ###
           # Calculate additional qalys for current practice
           
           additional_qalys_cp <- numeric(n_cycles + 1)
           
           # Calculate additional QALYs for current practice
           for (i in 2:(n_cycles + 1)) {
             additional_qalys_cp[i] <- 0  # Reset to 0 for each cycle
             
             # from waitlist health state
             
             transitions_to_DBD_SCD_good <-
               m_M_current_practice[i - 1, "On waitlist"] * m_P_current_practice["On waitlist", "DBD SCD good"]
             
             transitions_to_DBD_SCD_moderate <-
               m_M_current_practice[i - 1, "On waitlist"] * m_P_current_practice["On waitlist", "DBD SCD moderate"]
             
             transitions_to_DBD_SCD_poor <-
               m_M_current_practice[i - 1, "On waitlist"] * m_P_current_practice["On waitlist", "DBD SCD poor"]
             
             transitions_to_DBD_ECD_good <-
               m_M_current_practice[i - 1, "On waitlist"] * m_P_current_practice["On waitlist", "DBD ECD good"]
             
             transitions_to_DBD_ECD_moderate <-
               m_M_current_practice[i - 1, "On waitlist"] * m_P_current_practice["On waitlist", "DBD ECD moderate"]
             
             transitions_to_DBD_ECD_poor <-
               m_M_current_practice[i - 1, "On waitlist"] * m_P_current_practice["On waitlist", "DBD ECD poor"]
             
             transitions_to_DCD_good <-
               m_M_current_practice[i - 1, "On waitlist"] * m_P_current_practice["On waitlist", "DCD good"]
             
             transitions_to_DCD_moderate <-
               m_M_current_practice[i - 1, "On waitlist"] * m_P_current_practice["On waitlist", "DCD moderate"]
             
             transitions_to_DCD_poor <-
               m_M_current_practice[i - 1, "On waitlist"] * m_P_current_practice["On waitlist", "DCD poor"]
             
             transitions_to_off_waitlist_from_waitlist <-
               m_M_current_practice[i - 1, "On waitlist"] * m_P_current_practice["On waitlist", "Off waitlist"]
             
             # Initialize to zero then accumulate QALYS
             additional_qalys_cp[i] <- additional_qalys_cp[i] +
               transitions_to_DBD_SCD_good * u_transplantation_gg_function  * cycle_length +
               transitions_to_DBD_SCD_moderate * u_transplantation_mg_function  * cycle_length +
               transitions_to_DBD_SCD_poor * u_transplantation_pg_function  * cycle_length +
               
               
               transitions_to_DBD_ECD_good * u_transplantation_gg_function  * cycle_length +
               transitions_to_DBD_ECD_moderate * u_transplantation_mg_function  * cycle_length +
               transitions_to_DBD_ECD_poor * u_transplantation_pg_function  * cycle_length +
               
               transitions_to_DCD_good * u_transplantation_gg_function  * cycle_length +
               transitions_to_DCD_moderate * u_transplantation_mg_function  * cycle_length +
               transitions_to_DCD_poor * u_transplantation_pg_function  * cycle_length +
               
               transitions_to_off_waitlist_from_waitlist * u_dialysis_temp_off_waitlist * cycle_length
             
             # from good, moderate, poor DBDSCD, DBD ECD, DCD donors
             
             ##
             transition_to_gg_functioning_dbdscd <-
               m_M_current_practice[i - 1, "DBD SCD good"] * m_P_current_practice["DBD SCD good", "Good graft DBD SCD"]
             
             additional_qalys_cp[i] <-
               additional_qalys_cp[i] + transition_to_gg_functioning_dbdscd * u_transplantation_gg_function * cycle_length
             
             ##
             transition_to_mg_functioning_dbdscd <-
               m_M_current_practice[i - 1, "DBD SCD moderate"] * m_P_current_practice["DBD SCD moderate", "Moderate graft DBD SCD"]
             
             additional_qalys_cp[i] <-
               additional_qalys_cp[i] + transition_to_mg_functioning_dbdscd * u_transplantation_mg_function * cycle_length
             
             ##
             transition_to_pg_functioning_dbdscd <-
               m_M_current_practice[i - 1, "DBD SCD poor"] * m_P_current_practice["DBD SCD poor", "Poor graft DBD SCD"]
             
             additional_qalys_cp[i] <-
               additional_qalys_cp[i] + transition_to_pg_functioning_dbdscd * u_transplantation_pg_function * cycle_length
             
             ##
             transition_to_gg_functioning_dbdecd <-
               m_M_current_practice[i - 1, "DBD ECD good"] * m_P_current_practice["DBD ECD good", "Good graft DBD ECD"]
             
             additional_qalys_cp[i] <-
               additional_qalys_cp[i] + transition_to_gg_functioning_dbdecd * u_transplantation_gg_function * cycle_length
             
             ##
             transition_to_mg_functioning_dbdecd <-
               m_M_current_practice[i - 1, "DBD ECD moderate"] * m_P_current_practice["DBD ECD moderate", "Moderate graft DBD ECD"]
             
             additional_qalys_cp[i] <-
               additional_qalys_cp[i] + transition_to_mg_functioning_dbdecd * u_transplantation_mg_function * cycle_length
             
             ##
             transition_to_pg_functioning_dbdecd <-
               m_M_current_practice[i - 1, "DBD ECD poor"] * m_P_current_practice["DBD ECD poor", "Poor graft DBD ECD"]
             
             additional_qalys_cp[i] <-
               additional_qalys_cp[i] + transition_to_pg_functioning_dbdecd * u_transplantation_pg_function * cycle_length
             
             ##
             transition_to_gg_functioning_dcd <-
               m_M_current_practice[i - 1, "DCD good"] * m_P_current_practice["DCD good", "Good graft DCD"]
             
             additional_qalys_cp[i] <-
               additional_qalys_cp[i] + transition_to_gg_functioning_dcd * u_transplantation_gg_function * cycle_length
             
             ##
             transition_to_mg_functioning_dcd <-
               m_M_current_practice[i - 1, "DCD moderate"] * m_P_current_practice["DCD moderate", "Moderate graft DCD"]
             
             additional_qalys_cp[i] <-
               additional_qalys_cp[i] + transition_to_mg_functioning_dcd * u_transplantation_mg_function * cycle_length
             
             ##
             transition_to_pg_functioning_dcd <-
               m_M_current_practice[i - 1, "DCD poor"] * m_P_current_practice["DCD poor", "Poor graft DCD"]
             
             additional_qalys_cp[i] <-
               additional_qalys_cp[i] + transition_to_pg_functioning_dcd * u_transplantation_pg_function * cycle_length
             
             ##
             for (state in c(
               "DBD SCD good",
               "DBD SCD moderate",
               "DBD SCD poor",
               "DBD ECD good",
               "DBD ECD moderate",
               "DBD ECD poor",
               "DCD good",
               "DCD moderate",
               "DCD poor"
             )) {
               transition_to_hiv <-
                 m_M_current_practice[i - 1, state] * m_P_current_practice[state, "HIV"]
               additional_qalys_cp[i] <-
                 additional_qalys_cp[i] + transition_to_hiv * u_HIV * cycle_length
             }
             
             # Add QALYs for HBV transitions from various states
             for (state in c(
               "DBD SCD good",
               "DBD SCD moderate",
               "DBD SCD poor",
               "DBD ECD good",
               "DBD ECD moderate",
               "DBD ECD poor",
               "DCD good",
               "DCD moderate",
               "DCD poor"
             )) {
               transition_to_hbv <-
                 m_M_current_practice[i - 1, state] * m_P_current_practice[state, "HBV"]
               additional_qalys_cp[i] <-
                 additional_qalys_cp[i] + transition_to_hbv * u_CHB_hepB * cycle_length
             }
             
             
             # Add QALYs for HCV transitions from various states
             for (state in c(
               "DBD SCD good",
               "DBD SCD moderate",
               "DBD SCD poor",
               "DBD ECD good",
               "DBD ECD moderate",
               "DBD ECD poor",
               "DCD good",
               "DCD moderate",
               "DCD poor"
             )) {
               transition_to_hcv <-
                 m_M_current_practice[i - 1, state] * m_P_current_practice[state, "HCV"]
               additional_qalys_cp[i] <-
                 additional_qalys_cp[i] + transition_to_hcv * u_CHC_hepC * cycle_length
             }
             
             # transitions from good graft functioning
             
             transitions_to_mg_dbdscd <-
               m_M_current_practice[i - 1, "Good graft DBD SCD"] * m_P_current_practice["Good graft DBD SCD", "Moderate graft DBD SCD"]
             
             transitions_to_pg_dbdscd <-
               m_M_current_practice[i - 1, "Good graft DBD SCD"] * m_P_current_practice["Good graft DBD SCD", "Poor graft DBD SCD"]
             
             transitions_to_mg_dbdecd <-
               m_M_current_practice[i - 1, "Good graft DBD ECD"] * m_P_current_practice["Good graft DBD ECD", "Moderate graft DBD ECD"]
             
             transitions_to_pg_dbdecd <-
               m_M_current_practice[i - 1, "Good graft DBD ECD"] * m_P_current_practice["Good graft DBD ECD", "Poor graft DBD ECD"]
             
             transitions_to_mg_dcd <-
               m_M_current_practice[i - 1, "Good graft DCD"] * m_P_current_practice["Good graft DCD", "Moderate graft DCD"]
             
             transitions_to_pg_dcd <-
               m_M_current_practice[i - 1, "Good graft DCD"] * m_P_current_practice["Good graft DCD", "Poor graft DCD"]
             
             additional_qalys_cp[i] <- additional_qalys_cp[i] +
               transitions_to_mg_dbdscd * u_transplantation_mg_function * cycle_length +
               transitions_to_pg_dbdscd * u_transplantation_pg_function * cycle_length +
               transitions_to_mg_dbdecd * u_transplantation_mg_function * cycle_length +
               transitions_to_pg_dbdecd * u_transplantation_pg_function * cycle_length +
               transitions_to_mg_dcd * u_transplantation_mg_function * cycle_length +
               transitions_to_pg_dcd * u_transplantation_pg_function * cycle_length
             
             # transitions from moderate graft functioning
             
             transitions_to_pg_dbdscd_mg <-
               m_M_current_practice[i - 1, "Moderate graft DBD SCD"] * m_P_current_practice["Moderate graft DBD SCD", "Poor graft DBD SCD"]
             
             
             transitions_to_pg_dbdecd_mg <-
               m_M_current_practice[i - 1, "Moderate graft DBD ECD"] * m_P_current_practice["Moderate graft DBD ECD", "Poor graft DBD ECD"]
             
             
             transitions_to_pg_dcd_mg <-
               m_M_current_practice[i - 1, "Moderate graft DCD"] * m_P_current_practice["Moderate graft DCD", "Poor graft DCD"]
             
             additional_qalys_cp[i] <- additional_qalys_cp[i] +
               transitions_to_pg_dbdscd_mg * u_transplantation_pg_function * cycle_length +
               transitions_to_pg_dbdecd_mg * u_transplantation_pg_function * cycle_length +
               transitions_to_pg_dcd_mg * u_transplantation_pg_function * cycle_length
             
             
             # transitions from poor graft functioning
             transitions_to_off_waitlist_dbdscd_pg <-
               m_M_current_practice[i - 1, "Poor graft DBD SCD"] * m_P_current_practice["Poor graft DBD SCD", "Off waitlist"]
             
             
             transitions_to_off_waitlist_dbdecd_pg <-
               m_M_current_practice[i - 1, "Poor graft DBD ECD"] * m_P_current_practice["Poor graft DBD ECD", "Off waitlist"]
             
             
             transitions_to_off_waitlist_dcd_pg <-
               m_M_current_practice[i - 1, "Poor graft DCD"] * m_P_current_practice["Poor graft DCD", "Off waitlist"]
             
             additional_qalys_cp[i] <- additional_qalys_cp[i] +
               transitions_to_off_waitlist_dbdscd_pg * u_dialysis_temp_off_waitlist * cycle_length +
               transitions_to_off_waitlist_dbdecd_pg * u_dialysis_temp_off_waitlist * cycle_length +
               transitions_to_off_waitlist_dcd_pg * u_dialysis_temp_off_waitlist * cycle_length
             
             # transitions from temporary off waitlist
             transitions_to_waitlist <-
               m_M_current_practice[i - 1, "Off waitlist"] * m_P_current_practice["Off waitlist", "On waitlist"]
             
             additional_qalys_cp[i] <- additional_qalys_cp[i] +
               transitions_to_waitlist * u_on_waitlist_dialysis * cycle_length
             
             
             # transitions from chb to comp cirr
             transitions_to_comp_cirr_hepB <-
               m_M_current_practice[i - 1, "HBV"] * m_P_current_practice["HBV", "Hep B Comp cirr"]
             
             additional_qalys_cp[i] <- additional_qalys_cp[i] +
               transitions_to_comp_cirr_hepB * u_CC_hepB * cycle_length
             
             # transitions from chb to hepat carci
             transitions_to_hcc_hepB <-
               m_M_current_practice[i - 1, "HBV"] * m_P_current_practice["HBV", "Hep B HCC"]
             
             additional_qalys_cp[i] <- additional_qalys_cp[i] +
               transitions_to_hcc_hepB * u_HCC_hepB * cycle_length
             
             # transitions from chb to spon clearance
             transitions_to_spon_clearance_hepB <-
               m_M_current_practice[i - 1, "HBV"] * m_P_current_practice["HBV", "Spon clearance"]
             
             additional_qalys_cp[i] <- additional_qalys_cp[i] +
               transitions_to_spon_clearance_hepB * u_sag_clearance * cycle_length
             
             
             # transitions to svr from hcv
             transition_to_SVR <-
               m_M_current_practice[i - 1, "HCV"] * m_P_current_practice["HCV", "SVR"]
             additional_qalys_cp[i] <-
               additional_qalys_cp[i] + transition_to_SVR * u_SVR_hepC  * cycle_length
             
             
             # transition to comp cirr from hcv
             transitions_to_comp_cirr_hepc <-
               m_M_current_practice[i - 1, "HCV"] * m_P_current_practice["HCV", "Hep C comp cirr"]
             
             additional_qalys_cp[i] <-
               additional_qalys_cp[i] + transitions_to_comp_cirr_hepc * u_CC_hepC  * cycle_length
             
             
             # transtiion to decomp cirr from comp cirr
             transitions_to_decomp_cirr_compcirr_hbv <-
               m_M_current_practice[i - 1, "Hep B Comp cirr"] * m_P_current_practice["Hep B Comp cirr", "Hep B Decomp cirr"]
             
             additional_qalys_cp[i] <-
               additional_qalys_cp[i] + transitions_to_decomp_cirr_compcirr_hbv * u_DC_hepB  * cycle_length
             
             transitions_to_decomp_cirr_compcirr_hcv <-
               m_M_current_practice[i - 1, "Hep C comp cirr"] * m_P_current_practice["Hep C comp cirr", "Hep C Decomp cirr"]
             
             additional_qalys_cp[i] <-
               additional_qalys_cp[i] + transitions_to_decomp_cirr_compcirr_hcv * u_DC_hepC  * cycle_length
             
             
             # transition to hcc from comp cirr
             transitions_to_hcc_compcirr_hbv <-
               m_M_current_practice[i - 1, "Hep B Comp cirr"] * m_P_current_practice["Hep B Comp cirr", "Hep B HCC"]
             
             additional_qalys_cp[i] <-
               additional_qalys_cp[i] + transitions_to_hcc_compcirr_hbv * u_HCC_hepB  * cycle_length
             
             
             transitions_to_hcc_compcirr_hcv <-
               m_M_current_practice[i - 1, "Hep C comp cirr"] * m_P_current_practice["Hep C comp cirr", "Hep C HCC"]
             
             additional_qalys_cp[i] <-
               additional_qalys_cp[i] + transitions_to_hcc_compcirr_hcv * u_HCC_hepC  * cycle_length
             
             
             # transition to hcc from decomp cirr
             transitions_to_hcc_decompcirr_hbv <-
               m_M_current_practice[i - 1, "Hep B Decomp cirr"] * m_P_current_practice["Hep B Decomp cirr", "Hep B HCC"]
             
             additional_qalys_cp[i] <-
               additional_qalys_cp[i] + transitions_to_hcc_decompcirr_hbv * u_HCC_hepB  * cycle_length
             
             transitions_to_hcc_decompcirr_hcv <-
               m_M_current_practice[i - 1, "Hep C Decomp cirr"] * m_P_current_practice["Hep C Decomp cirr", "Hep C HCC"]
             
             additional_qalys_cp[i] <-
               additional_qalys_cp[i] + transitions_to_hcc_decompcirr_hcv * u_HCC_hepC  * cycle_length
             
             
             # transition to lt from decomp cirr
             transition_to_lt_decomp_cirr_hbv <-
               m_M_current_practice[i - 1, "Hep B Decomp cirr"] * m_P_current_practice["Hep B Decomp cirr", "Liver transplant 3"]
             
             additional_qalys_cp[i] <-
               additional_qalys_cp[i] + transition_to_lt_decomp_cirr_hbv * u_liver_transplant_year_1  * cycle_length
             
             transition_to_lt_decomp_cirr_hcv <-
               m_M_current_practice[i - 1, "Hep C Decomp cirr"] * m_P_current_practice["Hep C Decomp cirr", "Liver transplant 3"]
             
             additional_qalys_cp[i] <-
               additional_qalys_cp[i] + transition_to_lt_decomp_cirr_hcv * u_liver_transplant_year_1  * cycle_length
             
             
             # transition to lt from hcc
             transition_to_lt_hcc_hbv <-
               m_M_current_practice[i - 1, "Hep B HCC"] * m_P_current_practice["Hep B HCC", "Liver transplant 3"]
             
             additional_qalys_cp[i] <-
               additional_qalys_cp[i] + transition_to_lt_hcc_hbv * u_liver_transplant_year_1  * cycle_length
             
             transition_to_lt_hcc_hcv <-
               m_M_current_practice[i - 1, "Hep C HCC"] * m_P_current_practice["Hep C HCC", "Liver transplant 3"]
             
             additional_qalys_cp[i] <-
               additional_qalys_cp[i] + transition_to_lt_hcc_hcv * u_liver_transplant_year_1  * cycle_length
             
             
             v_qalys_cp[i] <- v_qalys_cp[i] + additional_qalys_cp[i]
           }
           
           
           
           # Proposed practice
           # Initialize vectors for base and additional costs
           v_cost_pp <- numeric(n_cycles + 1)
           v_qalys_pp <- numeric(n_cycles + 1)
           
           # Calculate base costs from state occupancies for both practices
           for (i in 1:(n_cycles + 1)) {
             v_cost_pp[i] <- sum(m_M_proposed_practice_sum[i, ] * v_c)
             v_qalys_pp[i] <- sum(m_M_proposed_practice_sum[i, ] * v_u)
           }
           
           additional_costs_pp <- numeric(n_cycles + 1)
           
           # Calculate additional costs for proposed practice
           for (i in 2:(n_cycles + 1)) {
             additional_costs_pp[i] <- 0  # Reset to 0 for each cycle
             
             transitions_to_DBD_SCD_good <-
               m_M_proposed_practice[i - 1, "On waitlist"] * m_P_proposed_practice["On waitlist", "DBD SCD good"]
             
             transitions_to_DBD_SCD_moderate <-
               m_M_proposed_practice[i - 1, "On waitlist"] * m_P_proposed_practice["On waitlist", "DBD SCD moderate"]
             
             transitions_to_DBD_SCD_poor <-
               m_M_proposed_practice[i - 1, "On waitlist"] * m_P_proposed_practice["On waitlist", "DBD SCD poor"]
             
             transitions_to_hcv_from_waitlist <-
               m_M_proposed_practice[i - 1, "On waitlist"] * m_P_proposed_practice["On waitlist", "HCV"]
             
             # Initialize to zero then accumulate costs
             additional_costs_pp[i] <-
               transitions_to_DBD_SCD_good * c_dbd_scd_good +
               transitions_to_DBD_SCD_moderate * c_dbd_scd_moderate +
               transitions_to_DBD_SCD_poor * c_dbd_scd_poor +
               transitions_to_hcv_from_waitlist * c_kt_hcv
             
             # hbv
             for (state in c(
               "DBD SCD good",
               "DBD SCD moderate",
               "DBD SCD poor",
               "DBD ECD good",
               "DBD ECD moderate",
               "DBD ECD poor",
               "DCD good",
               "DCD moderate",
               "DCD poor"
             )) {
               transition_to_hbv <-
                 m_M_proposed_practice[i - 1, state] * m_P_proposed_practice[state, "HBV"]
               additional_costs_pp[i] <-
                 additional_costs_pp[i] + transition_to_hbv * c_diagnosing_hepB
             }
             
             # hiv
             for (state in c(
               "DBD SCD good",
               "DBD SCD moderate",
               "DBD SCD poor",
               "DBD ECD good",
               "DBD ECD moderate",
               "DBD ECD poor",
               "DCD good",
               "DCD moderate",
               "DCD poor"
             )) {
               transition_to_hiv <-
                 m_M_proposed_practice[i - 1, state] * m_P_proposed_practice[state, "HIV"]
               additional_costs_pp[i] <-
                 additional_costs_pp[i] + transition_to_hiv * c_diagnosing_HIV
             }
             
             # hcv
             for (state in c(
               "DBD SCD good",
               "DBD SCD moderate",
               "DBD SCD poor",
               "DBD ECD good",
               "DBD ECD moderate",
               "DBD ECD poor",
               "DCD good",
               "DCD moderate",
               "DCD poor"
             )) {
               transition_to_hcv <-
                 m_M_proposed_practice[i - 1, state] * m_P_proposed_practice[state, "HCV"]
               additional_costs_pp[i] <-
                 additional_costs_pp[i] + transition_to_hcv * c_treating_hepC
             }
             
             # back to waitlist
             
             transition_to_waitlist <-
               m_M_proposed_practice[i - 1, "Off waitlist"] * m_P_proposed_practice["Off waitlist", "On waitlist"]
             additional_costs_pp[i] <-
               additional_costs_pp[i] + transition_to_waitlist * c_work_up_transplant_waitlist
             
             # to compensated cirr
             transtion_to_comp_cirr_hbv <-
               m_M_proposed_practice[i - 1, "HBV"] * m_P_proposed_practice["HBV", "Hep B Comp cirr"]
             additional_costs_pp[i] <-
               additional_costs_pp[i] + transtion_to_comp_cirr_hbv * c_one_off_transition_to_CC
             
             transtion_to_comp_cirr_hcv <-
               m_M_proposed_practice[i - 1, "HCV"] * m_P_proposed_practice["HCV", "Hep C comp cirr"]
             additional_costs_pp[i] <-
               additional_costs_pp[i] + transtion_to_comp_cirr_hcv * c_one_off_transition_to_CC
             
             # to hcc
             transition_to_hcc_hbv <-
               m_M_proposed_practice[i - 1, "HBV"] * m_P_proposed_practice["HBV", "Hep B HCC"]
             additional_costs_pp[i] <-
               additional_costs_pp[i] + transition_to_hcc_hbv * c_one_off_transition_to_hcc
             
             transition_to_hcc_hbv_comp <-
               m_M_proposed_practice[i - 1, "Hep B Comp cirr"] * m_P_proposed_practice["Hep B Comp cirr", "Hep B HCC"]
             additional_costs_pp[i] <-
               additional_costs_pp[i] + transition_to_hcc_hbv_comp * c_one_off_transition_to_hcc
             
             transition_to_hcc_hcv_comp <-
               m_M_proposed_practice[i - 1, "Hep C comp cirr"] * m_P_proposed_practice["Hep C comp cirr", "Hep C HCC"]
             additional_costs_pp[i] <-
               additional_costs_pp[i] + transition_to_hcc_hcv_comp * c_one_off_transition_to_hcc
             
             transition_to_hcc_hbv_decomp <-
               m_M_proposed_practice[i - 1, "Hep B Decomp cirr"] * m_P_proposed_practice["Hep B Decomp cirr", "Hep B HCC"]
             additional_costs_pp[i] <-
               additional_costs_pp[i] + transition_to_hcc_hbv_decomp * c_one_off_transition_to_hcc
             
             transition_to_hcc_hcv_decomp <-
               m_M_proposed_practice[i - 1, "Hep C Decomp cirr"] * m_P_proposed_practice["Hep C Decomp cirr", "Hep C HCC"]
             additional_costs_pp[i] <-
               additional_costs_pp[i] + transition_to_hcc_hcv_decomp * c_one_off_transition_to_hcc
             
             # to SVR
             transition_to_SVR <-
               m_M_proposed_practice[i - 1, "HCV"] * m_P_proposed_practice["HCV", "SVR"]
             additional_costs_pp[i] <-
               additional_costs_pp[i] + transition_to_SVR * c_SVR_hepC
             
             v_cost_pp[i] <- v_cost_pp[i] + additional_costs_pp[i]
           }
           
           
           ### Transition qalys ###
           # Calculate additional qalys for proposed practice
           
           additional_qalys_pp <- numeric(n_cycles + 1)
           
           # Calculate additional QALYs for proposed practice
           for (i in 2:(n_cycles + 1)) {
             additional_qalys_pp[i] <- 0  # Reset to 0 for each cycle
             
             # from waitlist health state
             
             transitions_to_DBD_SCD_good <-
               m_M_proposed_practice[i - 1, "On waitlist"] * m_P_proposed_practice["On waitlist", "DBD SCD good"]
             
             transitions_to_DBD_SCD_moderate <-
               m_M_proposed_practice[i - 1, "On waitlist"] * m_P_proposed_practice["On waitlist", "DBD SCD moderate"]
             
             transitions_to_DBD_SCD_poor <-
               m_M_proposed_practice[i - 1, "On waitlist"] * m_P_proposed_practice["On waitlist", "DBD SCD poor"]
             
             transitions_to_DBD_ECD_good <-
               m_M_proposed_practice[i - 1, "On waitlist"] * m_P_proposed_practice["On waitlist", "DBD ECD good"]
             
             transitions_to_DBD_ECD_moderate <-
               m_M_proposed_practice[i - 1, "On waitlist"] * m_P_proposed_practice["On waitlist", "DBD ECD moderate"]
             
             transitions_to_DBD_ECD_poor <-
               m_M_proposed_practice[i - 1, "On waitlist"] * m_P_proposed_practice["On waitlist", "DBD ECD poor"]
             
             transitions_to_DCD_good <-
               m_M_proposed_practice[i - 1, "On waitlist"] * m_P_proposed_practice["On waitlist", "DCD good"]
             
             transitions_to_DCD_moderate <-
               m_M_proposed_practice[i - 1, "On waitlist"] * m_P_proposed_practice["On waitlist", "DCD moderate"]
             
             transitions_to_DCD_poor <-
               m_M_proposed_practice[i - 1, "On waitlist"] * m_P_proposed_practice["On waitlist", "DCD poor"]
             
             transitions_to_hcv_from_waitlist <-
               m_M_proposed_practice[i - 1, "On waitlist"] * m_P_proposed_practice["On waitlist", "HCV"]
             
             transitions_to_off_waitlist_from_waitlist <-
               m_M_proposed_practice[i - 1, "On waitlist"] * m_P_proposed_practice["On waitlist", "Off waitlist"]
             
             # Initialize to zero then accumulate QALYS
             additional_qalys_pp[i] <- additional_qalys_pp[i] +
               transitions_to_DBD_SCD_good * u_transplantation_gg_function  * cycle_length +
               transitions_to_DBD_SCD_moderate * u_transplantation_mg_function  * cycle_length +
               transitions_to_DBD_SCD_poor * u_transplantation_pg_function  * cycle_length +
               
               transitions_to_DBD_ECD_good * u_transplantation_gg_function  * cycle_length +
               transitions_to_DBD_ECD_moderate * u_transplantation_mg_function  * cycle_length +
               transitions_to_DBD_ECD_poor * u_transplantation_pg_function  * cycle_length +
               
               transitions_to_DCD_good * u_transplantation_gg_function  * cycle_length +
               transitions_to_DCD_moderate * u_transplantation_mg_function  * cycle_length +
               transitions_to_DCD_poor * u_transplantation_pg_function  * cycle_length +
               
               transitions_to_hcv_from_waitlist * u_CHC_hepC  * cycle_length +
               
               transitions_to_off_waitlist_from_waitlist * u_dialysis_temp_off_waitlist * cycle_length
             
             # from good, moderate, poor DBDSCD, DBD ECD, DCD donors
             
             ##
             transition_to_gg_functioning_dbdscd <-
               m_M_proposed_practice[i - 1, "DBD SCD good"] * m_P_proposed_practice["DBD SCD good", "Good graft DBD SCD"]
             
             additional_qalys_pp[i] <-
               additional_qalys_pp[i] + transition_to_gg_functioning_dbdscd * u_transplantation_gg_function * cycle_length
             
             ##
             transition_to_mg_functioning_dbdscd <-
               m_M_proposed_practice[i - 1, "DBD SCD moderate"] * m_P_proposed_practice["DBD SCD moderate", "Moderate graft DBD SCD"]
             
             additional_qalys_pp[i] <-
               additional_qalys_pp[i] + transition_to_mg_functioning_dbdscd * u_transplantation_mg_function * cycle_length
             
             ##
             transition_to_pg_functioning_dbdscd <-
               m_M_proposed_practice[i - 1, "DBD SCD poor"] * m_P_proposed_practice["DBD SCD poor", "Poor graft DBD SCD"]
             
             additional_qalys_pp[i] <-
               additional_qalys_pp[i] + transition_to_pg_functioning_dbdscd * u_transplantation_pg_function * cycle_length
             
             ##
             transition_to_gg_functioning_dbdecd <-
               m_M_proposed_practice[i - 1, "DBD ECD good"] * m_P_proposed_practice["DBD ECD good", "Good graft DBD ECD"]
             
             additional_qalys_pp[i] <-
               additional_qalys_pp[i] + transition_to_gg_functioning_dbdecd * u_transplantation_gg_function * cycle_length
             
             ##
             transition_to_mg_functioning_dbdecd <-
               m_M_proposed_practice[i - 1, "DBD ECD moderate"] * m_P_proposed_practice["DBD ECD moderate", "Moderate graft DBD ECD"]
             
             additional_qalys_pp[i] <-
               additional_qalys_pp[i] + transition_to_mg_functioning_dbdecd * u_transplantation_mg_function * cycle_length
             
             ##
             transition_to_pg_functioning_dbdecd <-
               m_M_proposed_practice[i - 1, "DBD ECD poor"] * m_P_proposed_practice["DBD ECD poor", "Poor graft DBD ECD"]
             
             additional_qalys_pp[i] <-
               additional_qalys_pp[i] + transition_to_pg_functioning_dbdecd * u_transplantation_pg_function * cycle_length
             
             ##
             transition_to_gg_functioning_dcd <-
               m_M_proposed_practice[i - 1, "DCD good"] * m_P_proposed_practice["DCD good", "Good graft DCD"]
             
             additional_qalys_pp[i] <-
               additional_qalys_pp[i] + transition_to_gg_functioning_dcd * u_transplantation_gg_function * cycle_length
             
             ##
             transition_to_mg_functioning_dcd <-
               m_M_proposed_practice[i - 1, "DCD moderate"] * m_P_proposed_practice["DCD moderate", "Moderate graft DCD"]
             
             additional_qalys_pp[i] <-
               additional_qalys_pp[i] + transition_to_mg_functioning_dcd * u_transplantation_mg_function * cycle_length
             
             ##
             transition_to_pg_functioning_dcd <-
               m_M_proposed_practice[i - 1, "DCD poor"] * m_P_proposed_practice["DCD poor", "Poor graft DCD"]
             
             additional_qalys_pp[i] <-
               additional_qalys_pp[i] + transition_to_pg_functioning_dcd * u_transplantation_pg_function * cycle_length
             
             ##
             for (state in c(
               "DBD SCD good",
               "DBD SCD moderate",
               "DBD SCD poor",
               "DBD ECD good",
               "DBD ECD moderate",
               "DBD ECD poor",
               "DCD good",
               "DCD moderate",
               "DCD poor"
             )) {
               transition_to_hiv <-
                 m_M_proposed_practice[i - 1, state] * m_P_proposed_practice[state, "HIV"]
               additional_qalys_pp[i] <-
                 additional_qalys_pp[i] + transition_to_hiv * u_HIV * cycle_length
             }
             
             # Add QALYs for HBV transitions from various states
             for (state in c(
               "DBD SCD good",
               "DBD SCD moderate",
               "DBD SCD poor",
               "DBD ECD good",
               "DBD ECD moderate",
               "DBD ECD poor",
               "DCD good",
               "DCD moderate",
               "DCD poor"
             )) {
               transition_to_hbv <-
                 m_M_proposed_practice[i - 1, state] * m_P_proposed_practice[state, "HBV"]
               additional_qalys_pp[i] <-
                 additional_qalys_pp[i] + transition_to_hbv * u_CHB_hepB * cycle_length
             }
             
             
             # Add QALYs for HCV transitions from various states
             for (state in c(
               "DBD SCD good",
               "DBD SCD moderate",
               "DBD SCD poor",
               "DBD ECD good",
               "DBD ECD moderate",
               "DBD ECD poor",
               "DCD good",
               "DCD moderate",
               "DCD poor"
             )) {
               transition_to_hcv <-
                 m_M_proposed_practice[i - 1, state] * m_P_proposed_practice[state, "HCV"]
               additional_qalys_pp[i] <-
                 additional_qalys_pp[i] + transition_to_hcv * u_CHC_hepC * cycle_length
             }
             
             # transitions from good graft functioning
             
             transitions_to_mg_dbdscd <-
               m_M_proposed_practice[i - 1, "Good graft DBD SCD"] * m_P_proposed_practice["Good graft DBD SCD", "Moderate graft DBD SCD"]
             
             transitions_to_pg_dbdscd <-
               m_M_proposed_practice[i - 1, "Good graft DBD SCD"] * m_P_proposed_practice["Good graft DBD SCD", "Poor graft DBD SCD"]
             
             transitions_to_mg_dbdecd <-
               m_M_proposed_practice[i - 1, "Good graft DBD ECD"] * m_P_proposed_practice["Good graft DBD ECD", "Moderate graft DBD ECD"]
             
             transitions_to_pg_dbdecd <-
               m_M_proposed_practice[i - 1, "Good graft DBD ECD"] * m_P_proposed_practice["Good graft DBD ECD", "Poor graft DBD ECD"]
             
             transitions_to_mg_dcd <-
               m_M_proposed_practice[i - 1, "Good graft DCD"] * m_P_proposed_practice["Good graft DCD", "Moderate graft DCD"]
             
             transitions_to_pg_dcd <-
               m_M_proposed_practice[i - 1, "Good graft DCD"] * m_P_proposed_practice["Good graft DCD", "Poor graft DCD"]
             
             additional_qalys_pp[i] <- additional_qalys_pp[i] +
               transitions_to_mg_dbdscd * u_transplantation_mg_function * cycle_length +
               transitions_to_pg_dbdscd * u_transplantation_pg_function * cycle_length +
               transitions_to_mg_dbdecd * u_transplantation_mg_function * cycle_length +
               transitions_to_pg_dbdecd * u_transplantation_pg_function * cycle_length +
               transitions_to_mg_dcd * u_transplantation_mg_function * cycle_length +
               transitions_to_pg_dcd * u_transplantation_pg_function * cycle_length
             
             # transitions from moderate graft functioning
             
             transitions_to_pg_dbdscd_mg <-
               m_M_proposed_practice[i - 1, "Moderate graft DBD SCD"] * m_P_proposed_practice["Moderate graft DBD SCD", "Poor graft DBD SCD"]
             
             
             transitions_to_pg_dbdecd_mg <-
               m_M_proposed_practice[i - 1, "Moderate graft DBD ECD"] * m_P_proposed_practice["Moderate graft DBD ECD", "Poor graft DBD ECD"]
             
             
             transitions_to_pg_dcd_mg <-
               m_M_proposed_practice[i - 1, "Moderate graft DCD"] * m_P_proposed_practice["Moderate graft DCD", "Poor graft DCD"]
             
             additional_qalys_pp[i] <- additional_qalys_pp[i] +
               transitions_to_pg_dbdscd_mg * u_transplantation_pg_function * cycle_length +
               transitions_to_pg_dbdecd_mg * u_transplantation_pg_function * cycle_length +
               transitions_to_pg_dcd_mg * u_transplantation_pg_function * cycle_length
             
             
             # transitions from poor graft functioning
             transitions_to_off_waitlist_dbdscd_pg <-
               m_M_proposed_practice[i - 1, "Poor graft DBD SCD"] * m_P_proposed_practice["Poor graft DBD SCD", "Off waitlist"]
             
             
             transitions_to_off_waitlist_dbdecd_pg <-
               m_M_proposed_practice[i - 1, "Poor graft DBD ECD"] * m_P_proposed_practice["Poor graft DBD ECD", "Off waitlist"]
             
             
             transitions_to_off_waitlist_dcd_pg <-
               m_M_proposed_practice[i - 1, "Poor graft DCD"] * m_P_proposed_practice["Poor graft DCD", "Off waitlist"]
             
             additional_qalys_pp[i] <- additional_qalys_pp[i] +
               transitions_to_off_waitlist_dbdscd_pg * u_dialysis_temp_off_waitlist * cycle_length +
               transitions_to_off_waitlist_dbdecd_pg * u_dialysis_temp_off_waitlist * cycle_length +
               transitions_to_off_waitlist_dcd_pg * u_dialysis_temp_off_waitlist * cycle_length
             
             # transitions from temporary off waitlist
             transitions_to_waitlist <-
               m_M_proposed_practice[i - 1, "Off waitlist"] * m_P_proposed_practice["Off waitlist", "On waitlist"]
             
             additional_qalys_pp[i] <- additional_qalys_pp[i] +
               transitions_to_waitlist * u_on_waitlist_dialysis * cycle_length
             
             
             # transitions from chb to comp cirr
             transitions_to_comp_cirr_hepB <-
               m_M_proposed_practice[i - 1, "HBV"] * m_P_proposed_practice["HBV", "Hep B Comp cirr"]
             
             additional_qalys_pp[i] <- additional_qalys_pp[i] +
               transitions_to_comp_cirr_hepB * u_CC_hepB * cycle_length
             
             # transitions from chb to hepat carci
             transitions_to_hcc_hepB <-
               m_M_proposed_practice[i - 1, "HBV"] * m_P_proposed_practice["HBV", "Hep B HCC"]
             
             additional_qalys_pp[i] <- additional_qalys_pp[i] +
               transitions_to_hcc_hepB * u_HCC_hepB * cycle_length
             
             # transitions from chb to spon clearance
             transitions_to_spon_clearance_hepB <-
               m_M_proposed_practice[i - 1, "HBV"] * m_P_proposed_practice["HBV", "Spon clearance"]
             
             additional_qalys_pp[i] <- additional_qalys_pp[i] +
               transitions_to_spon_clearance_hepB * u_sag_clearance * cycle_length
             
             
             # transitions to svr from hcv
             transition_to_SVR <-
               m_M_proposed_practice[i - 1, "HCV"] * m_P_proposed_practice["HCV", "SVR"]
             additional_qalys_pp[i] <-
               additional_qalys_pp[i] + transition_to_SVR * u_SVR_hepC  * cycle_length
             
             
             # transition to comp cirr from hcv
             transitions_to_comp_cirr_hepc <-
               m_M_proposed_practice[i - 1, "HCV"] * m_P_proposed_practice["HCV", "Hep C comp cirr"]
             
             additional_qalys_pp[i] <-
               additional_qalys_pp[i] + transitions_to_comp_cirr_hepc * u_CC_hepC  * cycle_length
             
             
             # transtiion to decomp cirr from comp cirr
             transitions_to_decomp_cirr_compcirr_hbv <-
               m_M_proposed_practice[i - 1, "Hep B Comp cirr"] * m_P_proposed_practice["Hep B Comp cirr", "Hep B Decomp cirr"]
             
             additional_qalys_pp[i] <-
               additional_qalys_pp[i] + transitions_to_decomp_cirr_compcirr_hbv * u_DC_hepB  * cycle_length
             
             transitions_to_decomp_cirr_compcirr_hcv <-
               m_M_proposed_practice[i - 1, "Hep C comp cirr"] * m_P_proposed_practice["Hep C comp cirr", "Hep C Decomp cirr"]
             
             additional_qalys_pp[i] <-
               additional_qalys_pp[i] + transitions_to_decomp_cirr_compcirr_hcv * u_DC_hepC  * cycle_length
             
             
             # transition to hcc from comp cirr
             transitions_to_hcc_compcirr_hbv <-
               m_M_proposed_practice[i - 1, "Hep B Comp cirr"] * m_P_proposed_practice["Hep B Comp cirr", "Hep B HCC"]
             
             additional_qalys_pp[i] <-
               additional_qalys_pp[i] + transitions_to_hcc_compcirr_hbv * u_HCC_hepB  * cycle_length
             
             
             transitions_to_hcc_compcirr_hcv <-
               m_M_proposed_practice[i - 1, "Hep C comp cirr"] * m_P_proposed_practice["Hep C comp cirr", "Hep C HCC"]
             
             additional_qalys_pp[i] <-
               additional_qalys_pp[i] + transitions_to_hcc_compcirr_hcv * u_HCC_hepC  * cycle_length
             
             
             # transition to hcc from decomp cirr
             transitions_to_hcc_decompcirr_hbv <-
               m_M_proposed_practice[i - 1, "Hep B Decomp cirr"] * m_P_proposed_practice["Hep B Decomp cirr", "Hep B HCC"]
             
             additional_qalys_pp[i] <-
               additional_qalys_pp[i] + transitions_to_hcc_decompcirr_hbv * u_HCC_hepB  * cycle_length
             
             transitions_to_hcc_decompcirr_hcv <-
               m_M_proposed_practice[i - 1, "Hep C Decomp cirr"] * m_P_proposed_practice["Hep C Decomp cirr", "Hep C HCC"]
             
             additional_qalys_pp[i] <-
               additional_qalys_pp[i] + transitions_to_hcc_decompcirr_hcv * u_HCC_hepC  * cycle_length
             
             
             # transition to lt from decomp cirr
             transition_to_lt_decomp_cirr_hbv <-
               m_M_proposed_practice[i - 1, "Hep B Decomp cirr"] * m_P_proposed_practice["Hep B Decomp cirr", "Liver transplant 3"]
             
             additional_qalys_pp[i] <-
               additional_qalys_pp[i] + transition_to_lt_decomp_cirr_hbv * u_liver_transplant_year_1  * cycle_length
             
             transition_to_lt_decomp_cirr_hcv <-
               m_M_proposed_practice[i - 1, "Hep C Decomp cirr"] * m_P_proposed_practice["Hep C Decomp cirr", "Liver transplant 3"]
             
             additional_qalys_pp[i] <-
               additional_qalys_pp[i] + transition_to_lt_decomp_cirr_hcv * u_liver_transplant_year_1  * cycle_length
             
             
             # transition to lt from hcc
             transition_to_lt_hcc_hbv <-
               m_M_proposed_practice[i - 1, "Hep B HCC"] * m_P_proposed_practice["Hep B HCC", "Liver transplant 3"]
             
             additional_qalys_pp[i] <-
               additional_qalys_pp[i] + transition_to_lt_hcc_hbv * u_liver_transplant_year_1  * cycle_length
             
             transition_to_lt_hcc_hcv <-
               m_M_proposed_practice[i - 1, "Hep C HCC"] * m_P_proposed_practice["Hep C HCC", "Liver transplant 3"]
             
             additional_qalys_pp[i] <-
               additional_qalys_pp[i] + transition_to_lt_hcc_hcv * u_liver_transplant_year_1  * cycle_length
             
             
             
             v_qalys_pp[i] <- v_qalys_pp[i] + additional_qalys_pp[i]
           }
           
           
           # within cycle correction  --------
           # first, we define two functions to identify if a number is even or odd
           is_even <- function(x) x %% 2 == 0
           is_odd <- function(x) x %% 2 != 0
           
           # Vector with cycles
           v_cycles <- seq(1, n_cycles + 1)
           
           # Generate 2/3 and 4/3 multipliers for even and odd entries, respectively
           v_wcc <- is_even(v_cycles) * (2 / 3) + is_odd(v_cycles) * (4 / 3)
           
           # Substitute 1/3 in first and last entries
           v_wcc[1] <- v_wcc[n_cycles + 1] <- 1 / 3
           
           # Discount weight for effects
           d_e <- 0.05
           d_c <- 0.05
           
           
           v_dwe <- 1 / ((1 + (d_e * cycle_length)) ^ (0:n_cycles))
           
           v_dwc <- 1 / ((1 + (d_c * cycle_length)) ^ (0:n_cycles))
           
           # Assume v_cost_cp and v_cost_pp include all transition-specific costs correctly
           # Compute total QALYs for each practice
           total_qaly_cp <- sum(v_qalys_cp)
           total_qaly_pp <- sum(v_qalys_pp)
           total_cost_cp <- sum(v_cost_cp)
           total_cost_pp <- sum(v_cost_pp)
           
           # Apply within-cycle correction and discounting
           n_tot_qaly_cp <- sum(v_qalys_cp * v_dwe * v_wcc)
           n_tot_cost_cp <- sum(v_cost_cp * v_dwc * v_wcc)
           n_tot_qaly_pp <- sum(v_qalys_pp * v_dwe * v_wcc)
           n_tot_cost_pp <- sum(v_cost_pp * v_dwc * v_wcc)
           
           # vector of costs
           v_costs_str <- c(n_tot_cost_cp, n_tot_cost_pp)
           v_qalys_str <- c(n_tot_qaly_cp, n_tot_qaly_pp)
           
           # calculate incremental cost-effectiveness ratios (ICER)
           v_names_str <- c("Current practice", "Proposed practice")
           
           df_cea <- calculate_icers(cost = v_costs_str,
                                              effect = v_qalys_str,
                                              strategies = v_names_str)
           
           return(list(Cost = c(n_tot_cost_cp, n_tot_cost_pp), 
            Effect = c(n_tot_qaly_cp, n_tot_qaly_pp)))
           
           
         })
  }
```

# Update parameters
```{r}
update_param_list <- function(l_params_all, params_updated){
  
  if (typeof(params_updated)!="list"){
    params_updated <- split(unname(params_updated),names(params_updated)) #converte the named vector to a list
  }
  l_params_all <- modifyList(l_params_all, params_updated) #update the values
  return(l_params_all)
}
```

