---
title: "Probabilistic sensitivity analysis"
author: "Karan Ketan Shah"
date: "2024-05-03"
output: html_document
Adapted from Alarid-Escudero F, Krijkamp E, Enns EA, et al. An introductory tutorial on cohort state-transition models in r using a cost-effectiveness analysis example. 2023;43(1):3-20
---

```{r , include=FALSE}
rm(list = ls())  # remove any variables in R's memory
options(scipen = 999)
```

# Load libraries
```{r load libraries, echo=FALSE}
library(tidyverse)
library(dplyr)
library(readxl)
library(SciViews)
library(dampack)
library(writexl)
library(ggplot2)
library(reshape2)
library(summarytools)
library(cowplot)
# library(dampack)
library(gridExtra)
library(patchwork)
library(grid)      # For textGrob


```

# Set directory
```{r set directory, echo=FALSE}
modelsloc <- 'C:/Users/kshah/OneDrive - The University of Sydney (Staff)/Markov vs microsim/Model/Markov model/R/'
inputsloc <-  'C:/Users/kshah/OneDrive - The University of Sydney (Staff)/Markov vs microsim/Model/Inputs'
figuresloc <- 'C:/Users/kshah/OneDrive - The University of Sydney (Staff)/Markov vs microsim/Model/Figures'

```

# Probabilistic sensitivity analysis
```{r}
# Create new environments
## Load model, CEA and PSA functions ----
rmarkdown::render("C:/Users/kshah/OneDrive - The University of Sydney (Staff)/Markov vs microsim/Model/Markov model/R/Functions - Markov model.Rmd")

envUtilities <- new.env()
rmarkdown::render("C:/Users/kshah/OneDrive - The University of Sydney (Staff)/Markov vs microsim/Model/Inputs/Script/Utilites.Rmd", envir = envUtilities)

envCosts <- new.env()
rmarkdown::render("C:/Users/kshah/OneDrive - The University of Sydney (Staff)/Markov vs microsim/Model/Inputs/Script/Costs.Rmd", envir = envCosts)

envTransProbs <- new.env()
rmarkdown::render("C:/Users/kshah/OneDrive - The University of Sydney (Staff)/Markov vs microsim/Model/Inputs/Script/Inputs for transition probabilities.Rmd", envir = envTransProbs)

n_sim <- 1000
c_diagosis_proposed_policy <- 3348.9


# Generate PSA input dataset
df_psa_input_probs <- envTransProbs$generate_psa_params_probs(n_sim = n_sim, seed = 922231, range_PSA = 0.2)
df_psa_input_costs <- envCosts$generate_psa_params_costs(n_sim = n_sim, seed = 922231, range_PSA = 0.2)
df_psa_input_utils <- envUtilities$generate_psa_params_qalys(n_sim = n_sim, seed = 922231, range_PSA = 0.2)

# Example using dplyr to join by a common key, such as 'simulation_id' if it exists
df_psa_combined <- cbind(df_psa_input_probs, df_psa_input_costs, df_psa_input_utils)

write.csv(df_psa_input_costs, file = file.path("C:/Users/kshah/OneDrive - The University of Sydney (Staff)/Markov vs microsim/Model/Markov model/R/cost_psa.csv"))
write.csv(df_psa_input_probs, file = file.path("C:/Users/kshah/OneDrive - The University of Sydney (Staff)/Markov vs microsim/Model/Markov model/R/probs_psa.csv"))
write.csv(df_psa_input_utils, file = file.path("C:/Users/kshah/OneDrive - The University of Sydney (Staff)/Markov vs microsim/Model/Markov model/R/utils_psa.csv"))


## Run PSA ----
# Initialize data.frames with PSA output 
# data.frame of costs
df_c <- as.data.frame(matrix(0, 
                             nrow = n_sim,
                             ncol = 2))
colnames(df_c) <- c("Cost_Current_Practice", "Cost_Proposed_Practice")

#* data.frame of effectiveness
df_e <- as.data.frame(matrix(0, 
                             nrow = n_sim,
                             ncol = 2))

colnames(df_e) <- c("Effect_Current_Practice", "Effect_Proposed_Practice")

#* Conduct probabilistic sensitivity analysis
#* Run Markov model on each parameter set of PSA input dataset
n_time_init_psa_series <- Sys.time()
for(i in 1:n_sim){
  l_psa_input <- update_param_list(l_params_all, df_psa_combined[i,])
  
  l_out_temp <- calculate_ce_out(l_psa_input)
  
  df_c[i, ] <- l_out_temp$Cost
  
  df_e[i, ] <- l_out_temp$Effect
  
  # Display simulation progress
  if(i/(n_sim/10) == round(i/(n_sim/10), 0)) { # display progress every 10%
    cat('\r', paste(i/n_sim * 100, "% done", sep = " "))
  }
}

n_time_end_psa_series <- Sys.time()
n_time_total_psa_series <- n_time_end_psa_series - n_time_init_psa_series
print(paste0("PSA with ", scales::comma(n_sim), " simulations run in series in ", 
             round(n_time_total_psa_series, 2), " ", 
             units(n_time_total_psa_series)))

## Visualize PSA results and CEA ----
source(file.path("C:/Users/kshah/OneDrive - The University of Sydney (Staff)/Markov vs microsim/Model/Markov model/R/Functions.R"))

l_psa <- make_psa_obj(cost          = df_c, 
                      effectiveness = df_e, 
                      parameters    = df_psa_combined, 
                      strategies    = v_names_str)

l_psa$strategies <- v_names_str
colnames(l_psa$effectiveness)<- v_names_str
colnames(l_psa$cost)<- v_names_str

#* Vector with willingness-to-pay (WTP) thresholds.
v_wtp <- seq(0, 50000, by = 5000)

### Cost-Effectiveness Scatter plot ----
scatter <- plot.psa(l_psa) +
  ggthemes::scale_color_colorblind() +
  ggthemes::scale_fill_colorblind() +
  xlab("Effectiveness (QALYs)") +
  guides(col = guide_legend(nrow = 2)) +
  theme(legend.position = "bottom")

figuresloc <- 'C:/Users/kshah/OneDrive - The University of Sydney (Staff)/Markov vs microsim/Model/Figures'

ggsave(filename = file.path(figuresloc, paste0("markov_psa_scatter_plot", gsub("-", "", Sys.Date()), ".png")),
       plot = scatter)

### Incremental cost-effectiveness ratios (ICERs) with probabilistic output ----
df_out_ce_psa <- summary.psa(l_psa)

df_cea_psa <- calculate_icers(
  cost       = df_out_ce_psa$meanCost,
  effect     = df_out_ce_psa$meanEffect,
  strategies = df_out_ce_psa$Strategy
)

df_cea_psa

### Plot cost-effectiveness frontier with probabilistic output 
icers_plot <- plot.icers(df_cea_psa)

ggsave(filename = file.path(figuresloc, paste0("markov_psa_icer_plot", gsub("-", "", Sys.Date()), ".png")),
       plot = icers_plot)

## Cost-effectiveness acceptability curves (CEACs) and frontier (CEAF) ---
ceac_obj <- ceac(wtp = v_wtp, psa = l_psa)
summary.ceac(ceac_obj)

#* CEAC & CEAF plot
ceac <- plot.ceac(ceac_obj) +
  ggthemes::scale_color_colorblind() +
  ggthemes::scale_fill_colorblind() +
  theme(legend.position = c(0.82, 0.5))

ggsave(filename = file.path(figuresloc, paste0("markov_ceac_icer_plot", gsub("-", "", Sys.Date()), ".png")),
       plot = ceac)

```

# Compare PSA distribution between TreeAge and R
```{r}
tree_age_psa <-
  read_excel(
    path = file.path(
      "C:/Users/kshah/OneDrive - The University of Sydney (Staff)/Markov vs microsim/Model/Markov model/Tree age model/Traces/Values, Dists, Trackers.xlsx"
    )
  )

# TreeAge
melt_psa_Tree <- melt(tree_age_psa, id.vars = "Iteration")

##
melt_cost_psa_Tree <- melt_psa_Tree %>% 
  filter(grepl("Cost|dist_c", variable))

##
melt_utils_psa_Tree <- melt_psa_Tree %>% 
  filter(grepl("Effectiveness|dist_u", variable))

##
melt_probs_psa_Tree <- melt_psa_Tree %>% 
  filter(grepl("tp|dist_r|dist_p", variable))

# R
#
melt_cost_psa_R <- melt(df_psa_input_costs) %>% 
  group_by(variable) %>% 
  mutate(Iteration = row_number()) %>% 
  ungroup() %>% 
  dplyr::select(Iteration, variable, value)

##
melt_utils_psa_R <- melt(df_psa_input_utils) %>% 
  group_by(variable) %>% 
  mutate(Iteration = row_number()) %>% 
  ungroup() %>% 
  dplyr::select(Iteration, variable, value)

##
melt_probs_psa_R <- melt(df_psa_input_probs) %>% 
  group_by(variable) %>% 
  mutate(Iteration = row_number()) %>% 
  ungroup() %>% 
  dplyr::select(Iteration, variable, value)


```

## Compare distribution of costs
```{r}
#extract names from both treeage and R cost psa files
var_names_tree <- unique(melt_cost_psa_Tree$variable)
var_names_R <- unique(melt_cost_psa_R$variable)

# Clean TreeAge variable names
melt_cost_psa_Tree$variable <- gsub("dist_", "", melt_cost_psa_Tree$variable)
melt_cost_psa_Tree$variable <- gsub(" Cost\r\n\\(", "", melt_cost_psa_Tree$variable)
melt_cost_psa_Tree$variable <- gsub("\\)", "", melt_cost_psa_Tree$variable)
melt_cost_psa_Tree$variable <- gsub(" ", "_", melt_cost_psa_Tree$variable)
melt_cost_psa_Tree$variable <- tolower(melt_cost_psa_Tree$variable)
+++
# Clean R variable names
melt_cost_psa_R$variable <- tolower(melt_cost_psa_R$variable)

# Identify common and unique variables
common_vars <- intersect(melt_cost_psa_Tree$variable, melt_cost_psa_R$variable)
unique_tree <- setdiff(melt_cost_psa_Tree$variable, melt_cost_psa_R$variable)
unique_R <- setdiff(melt_cost_psa_R$variable, melt_cost_psa_Tree$variable)

# Print to check
print(common_vars)
print(unique_tree)
print(unique_R)

summary(melt_cost_psa_R)
melt_cost_psa_Tree$value <- as.numeric(melt_cost_psa_Tree$value)
melt_cost_psa_Tree$Iteration <- as.numeric(melt_cost_psa_Tree$Iteration)
summary(melt_cost_psa_Tree)

# for(var in common_vars) {
#   # Filter data for the current variable
#   data_tree <- melt_cost_psa_Tree[melt_cost_psa_Tree$variable == var, ]
#   data_R <- melt_cost_psa_R[melt_cost_psa_R$variable == var, ]
# 
#   # Plotting the densities
#   p <- ggplot() +
#     geom_density(data = data_tree, aes(x = value), fill = "blue", alpha = 0.5) +
#     geom_density(data = data_R, aes(x = value), fill = "red", alpha = 0.5) +
#     ggtitle(paste("Distribution of", var))
# 
#   print(p)
# }


# Create a list to store all plots
plots <- list()

# Create a separate plot for the legend
legend_plot <- ggplot() +
  geom_density(data = data.frame(value = rnorm(100)), aes(x = value), fill = "blue", alpha = 0.5) +
  geom_density(data = data.frame(value = rnorm(100, mean = 2)), aes(x = value), fill = "red", alpha = 0.5) +
  scale_fill_manual(values = c("blue" = "TreeAge", "red" = "R")) +
  theme(legend.position = "bottom") +
  guides(fill = guide_legend(title = "Legend"))

for (var in common_vars) {
  # Filter data for the current variable
  data_tree <- melt_cost_psa_Tree[melt_cost_psa_Tree$variable == var, ]
  data_R <- melt_cost_psa_R[melt_cost_psa_R$variable == var, ]

  # Clean the variable name to remove 'dist_'
  var_name <- sub("dist_", "", var)

  # Plotting the densities
  p <- ggplot() +
    geom_density(data = data_tree, aes(x = value, fill = "TreeAge"), alpha = 0.5) +
    geom_density(data = data_R, aes(x = value, fill = "R"), alpha = 0.5) +
    scale_fill_manual(values = c("TreeAge" = "blue", "R" = "red")) +
    ggtitle(paste("Distribution of", var_name)) +
    theme(legend.position = "none")

  # Add plot to the list
  plots[[var]] <- p
}

# Combine plots in a grid with 5 columns and add the legend
combined_plot <- wrap_plots(plots, ncol = 5) + plot_layout(guides = "collect") & theme(legend.position = 'bottom')


# Save the combined plot
ggsave(file = file.path(figuresloc, "dist_cost.pdf"), combined_plot, width = 20, height = 20, dpi = 300)  # You can adjust the size

```


## Compare distribution of utilities
```{r}
#extract names from both treeage and R cost psa files
var_names_tree <- unique(melt_utils_psa_Tree$variable)
var_names_R <- unique(melt_utils_psa_R$variable)

# Clean TreeAge variable names
melt_utils_psa_Tree$variable <- gsub("dist_", "", melt_utils_psa_Tree$variable)
melt_utils_psa_Tree$variable <- gsub(" Effectiveness\r\n\\(", "", melt_utils_psa_Tree$variable)
melt_utils_psa_Tree$variable <- gsub("\\)", "", melt_utils_psa_Tree$variable)
melt_utils_psa_Tree$variable <- gsub(" ", "_", melt_utils_psa_Tree$variable)
melt_utils_psa_Tree$variable <- tolower(melt_utils_psa_Tree$variable)

# Clean R variable names
melt_utils_psa_R$variable <- tolower(melt_utils_psa_R$variable)

# Identify common and unique variables
common_vars <- intersect(melt_utils_psa_Tree$variable, melt_utils_psa_R$variable)
unique_tree <- setdiff(melt_utils_psa_Tree$variable, melt_utils_psa_R$variable)
unique_R <- setdiff(melt_utils_psa_R$variable, melt_utils_psa_Tree$variable)

# Print to check
print(common_vars)
print(unique_tree)
print(unique_R)

melt_utils_psa_R <- melt_utils_psa_R %>%
  mutate(variable = ifelse(variable == "u_sag_clearance", "u_sag_clearance_hepb", variable))

summary(melt_utils_psa_R)
melt_utils_psa_Tree$value <- as.numeric(melt_utils_psa_Tree$value)
melt_utils_psa_Tree$Iteration <- as.numeric(melt_utils_psa_Tree$Iteration)
summary(melt_utils_psa_Tree)

# for(var in common_vars) {
#   # Filter data for the current variable
#   data_tree <- melt_utils_psa_Tree[melt_utils_psa_Tree$variable == var, ]
#   data_R <- melt_utils_psa_R[melt_utils_psa_R$variable == var, ]
# 
#   # Plotting the densities
#   p <- ggplot() +
#     geom_density(data = data_tree, aes(x = value), fill = "blue", alpha = 0.5) +
#     geom_density(data = data_R, aes(x = value), fill = "red", alpha = 0.5) +
#     ggtitle(paste("Distribution of", var))
# 
#   print(p)
# }


# Create a list to store all plots
plots <- list()

# Create a separate plot for the legend
legend_plot <- ggplot() +
  geom_density(data = data.frame(value = rnorm(100)), aes(x = value), fill = "blue", alpha = 0.5) +
  geom_density(data = data.frame(value = rnorm(100, mean = 2)), aes(x = value), fill = "red", alpha = 0.5) +
  scale_fill_manual(values = c("blue" = "TreeAge", "red" = "R")) +
  theme(legend.position = "bottom") +
  guides(fill = guide_legend(title = "Legend"))

for (var in common_vars) {
  # Filter data for the current variable
  data_tree <- melt_utils_psa_Tree[melt_utils_psa_Tree$variable == var, ]
  data_R <- melt_utils_psa_R[melt_utils_psa_R$variable == var, ]

  # Clean the variable name to remove 'dist_'
  var_name <- sub("dist_", "", var)

  # Plotting the densities
  p <- ggplot() +
    geom_density(data = data_tree, aes(x = value, fill = "TreeAge"), alpha = 0.5) +
    geom_density(data = data_R, aes(x = value, fill = "R"), alpha = 0.5) +
    scale_fill_manual(values = c("TreeAge" = "blue", "R" = "red")) +
    ggtitle(paste("Distribution of", var_name)) +
    theme(legend.position = "none")

  # Add plot to the list
  plots[[var]] <- p
}

# Combine plots in a grid with 5 columns and add the legend
combined_plot_utils <- wrap_plots(plots, ncol = 5) + plot_layout(guides = "collect") & theme(legend.position = 'bottom')


# Save the combined plot
ggsave(file = file.path(figuresloc, "dist_utils.pdf"), combined_plot_utils, width = 20, height = 20, dpi = 300)  # You can adjust the size

```

## Compare distribution of probabilities and rates
### Change names for the treeage probs to match those of R probs
```{r}
# Generate PSA input dataset
df_psa_input_rates <- envTransProbs$generate_psa_params_rates(n_sim = n_sim, seed = 922231, range = 0.20)

write.csv(df_psa_input_rates, file = file.path("C:/Users/kshah/OneDrive - The University of Sydney (Staff)/Markov vs microsim/Model/Markov model/R/rates_psa.csv"))

melt_rates_psa_R <- melt(df_psa_input_rates) %>% 
  group_by(variable) %>% 
  mutate(Iteration = row_number()) %>% 
  ungroup() %>% 
  dplyr::select(Iteration, variable, value)


melt_probs_psa_Tree$variable <- gsub("dist_", "", melt_probs_psa_Tree$variable)


#extract names from both treeage and R cost psa files
var_names_tree <- unique(melt_probs_psa_Tree$variable)
var_names_R <- unique(melt_rates_psa_R$variable)

# Identify common and unique variables
common_vars <- intersect(melt_probs_psa_Tree$variable, melt_rates_psa_R$variable)
unique_tree <- setdiff(melt_probs_psa_Tree$variable, melt_rates_psa_R$variable)
unique_R <- setdiff(melt_rates_psa_R$variable, melt_probs_psa_Tree$variable)

melt_rates_psa_R$variable <- as.character(melt_rates_psa_R$variable)

melt_rates_psa_R <- melt_rates_psa_R %>%
  mutate(variable = ifelse(variable == "p_taken__off_waitlist_A", "p_taken_off_waitlist_A", variable))

melt_rates_psa_R <- melt_rates_psa_R %>%
  mutate(variable = ifelse(variable == "r_post_transplant_HCV", "r_post_transplant_hepC", variable))

melt_rates_psa_R <- melt_rates_psa_R %>%
  mutate(variable = ifelse(variable == "tp_death_functioning_graft", "r_death_functioning_graft", variable))

common_vars <- intersect(melt_probs_psa_Tree$variable, melt_rates_psa_R$variable)
unique_tree <- setdiff(melt_probs_psa_Tree$variable, melt_rates_psa_R$variable)
unique_R <- setdiff(melt_rates_psa_R$variable, melt_probs_psa_Tree$variable)


summary(melt_rates_psa_R)
melt_probs_psa_Tree$value <- as.numeric(melt_probs_psa_Tree$value)
melt_probs_psa_Tree$Iteration <- as.numeric(melt_probs_psa_Tree$Iteration)
summary(melt_probs_psa_Tree)

# Create a list to store all plots
plots <- list()

# Create a separate plot for the legend
legend_plot <- ggplot() +
  geom_density(data = data.frame(value = rnorm(100)), aes(x = value), fill = "blue", alpha = 0.5) +
  geom_density(data = data.frame(value = rnorm(100, mean = 2)), aes(x = value), fill = "red", alpha = 0.5) +
  scale_fill_manual(values = c("blue" = "TreeAge", "red" = "R")) +
  theme(legend.position = "bottom") +
  guides(fill = guide_legend(title = "Legend"))

for (var in common_vars) {
  # Filter data for the current variable
  data_tree <- melt_probs_psa_Tree[melt_probs_psa_Tree$variable == var, ]
  data_R <- melt_rates_psa_R[melt_rates_psa_R$variable == var, ]

  # Clean the variable name to remove 'dist_'
  var_name <- sub("dist_", "", var)

  # Plotting the densities
  p <- ggplot() +
    geom_density(data = data_tree, aes(x = value, fill = "TreeAge"), alpha = 0.5) +
    geom_density(data = data_R, aes(x = value, fill = "R"), alpha = 0.5) +
    scale_fill_manual(values = c("TreeAge" = "blue", "R" = "red")) +
    ggtitle(paste("Distribution of", var_name)) +
    theme(legend.position = "none")

  # Add plot to the list
  plots[[var]] <- p
}

# Combine plots in a grid with 5 columns and add the legend
combined_plot_probs <- wrap_plots(plots, ncol = 5) + plot_layout(guides = "collect") & theme(legend.position = 'bottom')

# Save the combined plot
ggsave(file = file.path(figuresloc, "dist_probs.pdf"), combined_plot_probs, width = 20, height = 20, dpi = 300)  # You can adjust the size
```

```{r}

```

